### ISSUE TITLE
GC_skew () issue

### ISSUE THREAD

**Issue by Cashalow** [biopython/biopython#1107]
Hello, 
I found a rather strange issue in the GC_skew() function in Bio.SeqUtils.
If you run this code : 

import Bio
import Bio.SeqUtils
from Bio.Seq import Seq

Bio.SeqUtils.GC_skew(Seq("G"*100 +"A"))

this will fail because GC_skew will try to calculate the skew on the last remaining nucleotide which is not a G/C. Should this function check before trying to divide by zero?

Cheers and thanks for the good work !

**Comment by peterjc** [comment]
You missed out the error, under Python 3.6 I get:

```
>>> import Bio
>>> import Bio.SeqUtils
>>> from Bio.Seq import Seq
>>> Bio.SeqUtils.GC_skew(Seq("G"*100 +"A"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/SeqUtils/__init__.py", line 106, in GC_skew
    skew = (g - c) / float(g + c)
ZeroDivisionError: float division by zero
```

This is a corner case, due to the windowing scheme the final chunk of sequence can be far smaller than the window size (here one base ``A`` rather than a window of 100bp), and it is therefore more likely to have no ``C`` or ``G`` and thus give a divide by zero exception.

What would you suggest be returned here? ``None`` or the special float value not-a-number (I forget now the best way to define NaN for cross platform and cross version compatibility - something like ``float("NaN")`` though I think).

**Comment by Cashalow** [comment]
Yes indeed but it could also happen with a theoretical window of only A/Ts. I am trying to see how other tools deal with this theoretical case and this one http://genskew.csb.univie.ac.at/ returns "0" when no G/C are found, which as far as I'm concerned makes sense because indeed no GC skew can be observed on such sequences.

**Comment by peterjc** [comment]
You could make a good case for returning zero here too.

**Comment by peterjc** [comment]
Would you like to submit a pull request returning zero in this cases (and explaining this in the docstring)?

Ideally please include a doctest or unittest for this as well.

**Comment by Cashalow** [comment]
Yes sorry, I have prepared the pull request but did not send it yet. I'll try to add a test as well then.
