### ISSUE TITLE
reverse_complement() removes id, name, and description

### ISSUE THREAD

**Issue by kcamnairb** [biopython/biopython#1363]
Hi, when I reverse compement a SeqRecord object, it no longer contains the name, id, or description. Is this the expected behavior? I would expect it to maintain these features and maybe indicate that it is reverse complemented. I am using Biopython 1.70 and python 3.5.2 on Ubuntu 14.

Here's an example:
```from Bio import SeqIO
from Bio.Seq import Seq
my_seq = SeqIO.SeqRecord(seq=Seq('TACTTCACCACCAATTTCAGACCTGTCCCAACTATCCGCGCGGTAATGATGAAT...ACT'), 
                   id='Chr2_A_oryzae_RIB40', name='Chr2_A_oryzae_RIB40', description='(6264705 nucleotides)', dbxrefs=[])
print(my_seq)
my_seq_rc = my_seq.reverse_complement()
print()
print(my_seq_rc)
```

> ID: Chr2_A_oryzae_RIB40
> Name: Chr2_A_oryzae_RIB40
> Description: (6264705 nucleotides)
> Number of features: 0
> Seq('TACTTCACCACCAATTTCAGACCTGTCCCAACTATCCGCGCGGTAATGATGAAT...ACT', Alphabet())
> 
> ID: <unknown id>
> Name: <unknown name>
> Description: <unknown description>
> Number of features: 0
> Seq('AGT...ATTCATCATTACCGCGCGGATAGTTGGGACAGGTCTGAAATTGGTGGTGAAGTA', Alphabet())

**Comment by peterjc** [comment]
This is by design, try ``help(my_seq.reverse_complement)`` which should show you the docstring, linked to here:

http://biopython.org/DIST/docs/api/Bio.SeqRecord.SeqRecord-class.html#reverse_complement

https://github.com/biopython/biopython/blob/biopython-170/Bio/SeqRecord.py#L985

In brief, once reverse complemented any accession or description is likely invalid, so is dropped by default to avoid propagating errors. If you want to keep these fields, use:

```python
my_seq_rc = my_seq.reverse_complement(id=True, name=True, description=True)
```

If you want to modify the fields, consider something like this:

```python
my_seq_rc = my_seq.reverse_complement(id=my_seq.id + "_rc",
                                      name=my_seq.id + "_rc",
                                      description=my_seq.description + " (reverse complement)")
```

**Comment by kcamnairb** [comment]
Thanks. That makes sense.

**Comment by peterjc** [comment]
Great :)
