### ISSUE TITLE
Fetch Protein domains??

### ISSUE THREAD

**Issue by EmanIsmail** [biopython/biopython#1494]
How can I fetch domains of protein from pfam DB?

**Comment by JoaoRodrigues** [comment]
@EmanIsmail: Biopython's issue tracker is not a 'generic' mailing list for bioinformatics. Questions such as this one would be better suited for [Biostars](https://www.biostars.org), [the Bioinformatics' Stack Exchange](https://bioinformatics.stackexchange.com), etc. Often, the databases you are trying to access have their own help pages (e.g. [PFAM's](http://pfam.xfam.org/help)) with examples on how to use their RESTful (or other type) of interfaces to download data programatically.

If you have a specific question about how to use Biopython to download domains from PFAM, please be more explicit. Consider giving a short example of what you want to achieve, including the snippets of code you have tried to use. Otherwise, we cannot (and honestly and most likely, will not) help you.
