### ISSUE TITLE
urllib2.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1629]
always get urllib2.HTTPError: HTTP Error 403: Forbidden while trying the examples of biopython tutorial

I am reporting a problem with biopython-1.71, Python version 3.6.5, and operating
system Ubuntu (bio-linux) as follows:

from Bio.Blast import NCBIWWW
result_handle = NCBIWWW.qblast("blastn", "nt", "8332116")

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

Give me the record of  8332116 accession number

### Actual behaviour

Traceback (most recent call last):
  File "/home/peter/n.py", line 2, in <module>
    result_handle = NCBIWWW.qblast("blastn", "nt", "8332116")

  File "/usr/lib/python2.7/dist-packages/Bio/Blast/NCBIWWW.py", line 123, in qblast
    handle = _urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

### Steps to reproduce
1-copy the code from the tutorial
2-run the code

**Comment by peterjc** [comment]
It works for me:

```
>>> from Bio.Blast import NCBIWWW
>>> result_handle = NCBIWWW.qblast("blastn", "nt", "8332116")
>>> print(result_handle.read())#
<?xml version="1.0"?>
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
<BlastOutput>
  <BlastOutput_program>blastn</BlastOutput_program>
  <BlastOutput_version>BLASTN 2.8.0+</BlastOutput_version>
...
```

So this means it is not the code, or the NCBI service which is the problem.

Also, check can you still use the NCBI web-interface fine from your browser? That might also help narrow down the issue.

I suspect the issue is with your local network (is there a firewall, proxy, or webfilter), or you or your site has been deliberately blocked by the NCBI. That can happen if an IP address has been abusing the servers, and depending how your network connection works, it could be all the users at your location appear from the NCBI side to be one very greedy user?

Please contact your local network administrators to see if there is anything at their end, and if not write to the NCBI including your public IP address so they can check from their end.

**Comment by peterhabib** [comment]
ok, thank you
