### ISSUE TITLE
SearchIO.read is combining completely distinct hits in PSL files into one giant hit

### ISSUE THREAD

**Issue by docmanny** [biopython/biopython#1638]
### Setup

I am reporting a problem with Biopython version 1.71dev0, Python version 3.6.4 (also tested on 3.4 and 3.5), and using Linux as follows:
```
3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:31:06) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
CPython
Linux-4.9.76-gentoo-r1-x86_64-Genuine_Intel-R-_CPU_@_2.10GHz-with-gentoo-2.4.1
1.71.dev0
```

### The Issue
Normally, when reading a psl file, SearchIO correctly interprets hits that have no overlapping regions to be distinct hits. However, when reading the UCSC PSL file corresponding to the hits for GJA10 [(here)](https://github.com/biopython/biopython/files/1972031/gja10_ucsc.psl.txt) in the elephant genome, LoxAfr3, it merges the separate hits into one super-hit.
```python
from Bio import SearchIO
x = SearchIO.read("./gja10_ucsc.psl", "blat-psl")
print(x)
```
```
Program: blat (<unknown version>)
  Query: GJA10 (543)
         <unknown description>
 Target: <unknown target>
   Hits: ----  -----  ----------------------------------------------------------
            #  # HSP  ID + description
         ----  -----  ----------------------------------------------------------
            0      2  scaffold_0  <unknown description>
            1      4  scaffold_34  <unknown description>
            2      1  scaffold_29  <unknown description>
            3      2  scaffold_127  <unknown description>
            4      1  scaffold_39  <unknown description>
            5      1  scaffold_31  <unknown description>
```
```python
print(x.hits[0])
```
```
Query: GJA10
       <unknown description>
  Hit: scaffold_0 (129759341)
       <unknown description>
 HSPs: ----  --------  ---------  ------  ---------------  ---------------------
          #   E-value  Bit score    Span      Query range              Hit range
       ----  --------  ---------  ------  ---------------  ---------------------
          0         ?          ?       ?          [0:481]    [75732336:75733782]
          1         ?          ?       ?           [0:92]    [40618170:40618446]
```
If one converts the file to a BED file using convert2bed or an equivalent tool, these are kept as two distinct hits as they should be. 

I cannot figure out any reason for why these would be merged as such, but a similar thing happens if you search PO3F2 in LoxAfr3 [(Results file)](https://github.com/biopython/biopython/files/1972057/PO3F2_ucsc.psl.txt) and load the results:
```python
from Bio import SearchIO
y = SearchIO.read("./PO3F2_ucsc.psl", "blat-psl")
print(y)
```
```
Program: blat (<unknown version>)
  Query: PO3F2 (443)
         <unknown description>
 Target: <unknown target>
   Hits: ----  -----  ----------------------------------------------------------
            #  # HSP  ID + description
         ----  -----  ----------------------------------------------------------
            0      2  scaffold_0  <unknown description>
            1      1  scaffold_27  <unknown description>
            2      1  scaffold_24  <unknown description>
            3      1  scaffold_34  <unknown description>
            4      1  scaffold_33  <unknown description>
            5      1  scaffold_4  <unknown description>
            6      1  scaffold_58  <unknown description>
            7      1  scaffold_13  <unknown description>
            8      1  scaffold_150  <unknown description>
            9      1  scaffold_1  <unknown description>
           10      1  scaffold_2  <unknown description>
           11      1  scaffold_51  <unknown description>
           12      1  scaffold_11  <unknown description>
```
```python
print(y.hits[0])
```
```
Query: PO3F2
       <unknown description>
  Hit: scaffold_0 (129759341)
       <unknown description>
 HSPs: ----  --------  ---------  ------  ---------------  ---------------------
          #   E-value  Bit score    Span      Query range              Hit range
       ----  --------  ---------  ------  ---------------  ---------------------
          0         ?          ?       ?          [0:443]    [65717679:65719091]
          1         ?          ?       ?        [308:411]    [29100376:29100685]
```

**Comment by bow** [comment]
Thanks for reporting this and including test files, @docmanny. I could reproduce what you also see, but I should say that this seems like expected behavior to me. Let me clarify below:

So what SearchIO considers a single `Hit` in PSL files are sequences whose `tName` column (the 14th column if the left-most is numbered 1). In turn, a `QueryResult` is whatever the result of a single query. In PSL, that is everything that has the same `qName` value, which lie on the 10th column.

Doing `cut -f10,14 gja10_ucsc.psl` shows the query ID - hit ID pairs that are present in the file. And since they all belong to one query, we can do `cut -f14 gja10_ucsc.psl | sort | uniq | wc -l` to count how many unique hits there are. Here I see that the number is the same as what SearchIO shows if you do `len(hits)`: 6.

What about the individual per-line result? I have a feeling this is what you meant by hits (please correct me if I'm wrong). In SearchIO, this is what is actually represented by the `HSP` object (high-scoring pair, taking BLAST's terminology), and they are what the `Hit` object actually contains (accessible via `hit.hsps`).

Since this is the per-line result, counting up all HSPs should give you the same number as the lines in the raw file. And indeed, this is what you get:

```
# raw file
$ cat gja10_ucsc.psl | wc -l
10

# via SearchIO
...
qresult = SearchIO.read("gja10_ucsc.psl", "blat-psl")
print("There are", sum(len(hit) for hit in qresult.hits), "hsps")
--
$ python script.py
There are 11 hsps
```

If you run the same commands + script on the `PO3F2_ucsc.psl` file, you should also see that the numbers agree: total number of hits == number of unique `tName` value, and total number of hsps == number of lines in the PSL file.

**Comment by bow** [comment]
@docmanny Any comments on the previous reply? Could you retrieve the values you need from the PSL files?

**Comment by docmanny** [comment]
Hi, sorry @bow for the silence. I do see what you mean, and after comparing the results of the same search to the equivalent search in BLAST, I can see where my confusion came from. What I wanted out of the BLAT files are the HSPs, rather than the Hits, as you inferred. Thank you!

**Comment by bow** [comment]
No worries ~ thanks for clarifying and good to hear you can query what you needed!
