### ISSUE TITLE
visualization of protein

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1660]
first, sorry for writing this question here but i didn't know how to pull request.

secondly, How To visualize The protein structure using Biopython?

**Comment by peterjc** [comment]
Biopython does not in itself offer protein structure visualisation.

I have locked this issue because every time you closed and opened this issue, it triggered an email to the volunteer project team, which was getting frustrating, and it was not clear if you had a real question or not.

You are welcome to open a new issue, or write to the mailing list, but please try to better describe your question.
