### ISSUE TITLE
Pathway module

### ISSUE THREAD

**Issue by taylor-scott** [biopython/biopython#1690]
I was wondering if there has been a discussion on the development of the Pathway module? What the ideal API is, how it's meant to be used, what work needs to be done, etc.

I found a partial thread in the mailing list archives (http://lists.open-bio.org/pipermail/biopython-dev/2001-August/000499.html) but the classes mentioned there don't match what's in the module.

So I'm wondering why development stopped on it? It looks like there hasn't been much other than formatting/documentation and a few bug fixes over the years.

Any information would be great.

**Comment by peterjc** [comment]
The code commits for ``Bio.Pathway`` date from 5 Nov 2001 by Tarjei Mikkelsen, so would likely have been written after the mailing list discussion in August 2001 which you linked to - the discussion with emails from Tarjey continued - with some follow up in September as well, e.g. http://lists.open-bio.org/pipermail/biopython-dev/2001-September/000593.html - but I have not read the rest of that public record.

As to why development stopped, it likely did everything the original authors needed of it, and there has been no direct interest since.

Note this is one of the modules which is short of unit test coverage, see also pull request #1673 which tries to address that.

**Comment by peterjc** [comment]
Since you didn't seem to have any follow up questions, I'm going to close this issue. Feel free to post back here, or try on the mailing for wider discussion. Thanks.
