### ISSUE TITLE
TravisCI: ReportLab 3.5.0 breaks tests under Python 2.7 and 3.5

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1737]
Noticed on some recent pull requests, e.g. https://github.com/biopython/biopython/pull/1735#issuecomment-405063386

Python 2.7.14,

```
======================================================================
FAIL: test_partial_diagram (test_GenomeDiagram.DiagramTest)
Construct and draw SVG and PDF for just part of a SeqRecord.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_GenomeDiagram.py", line 770, in test_partial_diagram
    == gdd.write_to_string('PDF').replace(b"\r\n", b"\n")
AssertionError
----------------------------------------------------------------------
```

and Python 3.5,

```
======================================================================
FAIL: test_partial_diagram (test_GenomeDiagram.DiagramTest)
Construct and draw SVG and PDF for just part of a SeqRecord.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_GenomeDiagram.py", line 770, in test_partial_diagram
    == gdd.write_to_string('PDF').replace(b"\r\n", b"\n")
AssertionError
----------------------------------------------------------------------
```

Given the timing it looks like the release of ReportLab 3.5.0 earlier this week is to blame, see https://pypi.org/project/reportlab/#history

e.g. Our weekly TravisCI cron job failed on the previously passing master branch:

https://travis-ci.org/biopython/biopython/builds/404526057

**Comment by peterjc** [comment]
Testing a workaround by pinning ReportLab 3.4
https://travis-ci.org/peterjc/biopython/builds/404681877

Note we currently only install ReportLab under Python 2.7 and 3.5, so that is why only those failed.

**Comment by rtf-const** [comment]
I finally realised the issue.
The assertion that fails is the one that simple checks that PDF file saved in a file binary equals to PDF saved as string. But reportlab add unique ID to each file, value of ID is depending on current timestamp, so the file generated now and after millisecod will be different because of different PDF ID.
But there is a way to switch out generating ID based on timestamp by setting "invariant" variable in reportlab config to true.
I just created the pull request #1753 that passes the tests without holding down reportlab version

**Comment by peterjc** [comment]
Good work @rtf-const :)

**Comment by peterjc** [comment]
This seems to affect AppVeyor as well,

```
======================================================================
FAIL: test_partial_diagram (test_GenomeDiagram.DiagramTest)
Construct and draw SVG and PDF for just part of a SeqRecord.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_GenomeDiagram.py", line 770, in test_partial_diagram
    == gdd.write_to_string('PDF').replace(b"\r\n", b"\n")
AssertionError
----------------------------------------------------------------------
```

Seen on a couple of pull requests recently.

**Comment by peterjc** [comment]
Pull request #1753 should have fixed the TravisCI problem, let's see what AppVeyor does...

**Comment by replabrobin** [comment]
Hi, I am maintainer of the reportlab package and this is a reverse bug pointed out to me by a debian person. It seems the issue here is actually a repeatability issue. The difference between the two versions of GD_region_linear.pdf is caused by an id embedded in the document so in one case it is

/ID [<9737910ac7bddb2a43b171782188193c> <9737910ac7bddb2a43b171782188193c>]

and in the other

/ID [<bd4cf3cf6c42cb10a877dfa985f75b32> <bd4cf3cf6c42cb10a877dfa985f75b32>]

the ID contains a timestamp. So you need to fix the timestamp using environment variable SOURCE_DATE_EPOCH. I attach a patch to latest code to fix.

[test_GenomeDiagram.patch.txt](https://github.com/biopython/biopython/files/2282957/test_GenomeDiagram.patch.txt)

FWIW I'm not sure why you are messing with '\r\n' etc etc. PDF is a binary format and should always be read/written as bytes. Writing as a text file in windows may well break the document for that reason. Hopefully

**Comment by peterjc** [comment]
Thanks Robin - following up on this from the ReportLab side is a welcome surprise.

Your patch sets a specific date, while @rtf-const toggled this setting:

```python
from reportlab import rl_config
rl_config.invariant = True
```

Our Linux (TravisCI) and Windows (AppVeyor) tests are now passing.

As to the ``\r\n`` special case in the comparison, that dates back to cfc38cecd5ef71c81b7ce1e59fb4ca3a3188aa3d and may reflect some confusion at the time when I was getting things to work under Python 2 and 3. Looking at that now, we should probably open the file in binary mode, and compare the byte strings (rather than opening in text mode where Python would by default try to do magic with line endings).

**Comment by peterjc** [comment]
Testing https://github.com/peterjc/biopython/tree/binary-pdf right now:

https://ci.appveyor.com/project/peterjc/biopython/build/0.0.261
https://travis-ci.org/peterjc/biopython/builds/415436696

**Comment by replabrobin** [comment]
Hi Peter, the alternative using rl_config is another way to do this; it changes other things in the PDF as well eg it removes pdf comments that might have python ids in so is probably preferred for this case.

**Comment by peterjc** [comment]
Test cleanup applied as c7b909e842139f82d87639f3080bc45ff9613cca - thanks @replabrobin

**Comment by peterjc** [comment]
Cross reference Debian issue:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913064
