### ISSUE TITLE
MMCIFIO not quoting correctly

### ISSUE THREAD

**Issue by Bernhard10** [biopython/biopython#1784]
MMCIFIO quotes `O5'` as `'O5''` instead of `"O5'"`.

I believe line  236 of [Bio.PDB.mmcifio](https://github.com/biopython/biopython/blob/2fda5c6120063e385411094e12ae231be7febc6b/Bio/PDB/mmcifio.py#L236) should be changed from `if "' " in val:` to `if "'" in val:` 

I'll run some more checks and submit a pullrequest soon.

**Comment by peterjc** [comment]
CC @jgreener64

**Comment by jgreener64** [comment]
Actually, I think this is okay as it is. `'O5''` is valid mmCIF and is correctly parsed, e.g.
```python
from Bio.PDB.MMCIF2Dict import MMCIF2Dict
d = MMCIF2Dict("1AKE.cif")
list(d._splitline("foo 'bar'' baz"))
```
gives
```
['foo', "bar'", 'baz']
```
This is allowed provided whitespace does not follow the quote, see point 15 here: https://www.iucr.org/resources/cif/spec/version1.1/cifsyntax. If other tools can't parse it, it's their problem I guess.

The conditional exists as it is because in `_requires_newline` we check that the string doesn't contain both `"' "` and `"\" "`. So when we come to decide which quote character to use, we should decide based on whether one of these is present.

The problem with changing `if "' " in val:` to `if "'" in val:` is that `foo'" bar` gets quoted as `"foo'" bar"`, which is invalid. I think there are a few examples in mmCIF files where this is the case as people have indicated triple prime with this kind of construction.

If you wanted to improve readability by preferring the double quote you could perhaps change `if "' " in val:` to `if "'" in val and "\" " not in val:`.

Let me know if you agree.

**Comment by Bernhard10** [comment]
Hi.
Thanks for looking into this. I was unaware that this is allowed in mmcif.
Indeed,  `'O5''` works fine. What caused issues with other tools was something unrelated.

Anyway, I noticed another issue when writing tests for the PR, I'll open another issue for that.

**Comment by jgreener64** [comment]
Thanks for fixing the other issue!
