### ISSUE TITLE
Fetching taxonomy via SeqIO.parse for GenBank of CP010426 does not work.

### ISSUE THREAD

**Issue by bioreps** [biopython/biopython#2051]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows: 

```python
3.6.3 (default, Oct 17 2017, 14:49:00)
[GCC 4.9.2]
CPython
Linux-3.16.0.4-amd64-x86_64-with-debian-8.2
1.73
```

### Expected behaviour

I use SeqIO.parse to parse this GenBank file: `https://www.ncbi.nlm.nih.gov/nuccore/CP010426`
The taxonomy string is a bit unusual, since it is just "Archaea".
But still I would expect a list with single element `Archaea`.

### Actual behaviour

However, if I fetch the strain via `record.annoations['Taxonomy']` the output is just an empty list.

### Steps to reproduce

```
for record in SeqIO.parse(handle, "genbank"):
  taxonomy = ";".join(record.annoations['Taxonomy'])
```

**Comment by peterjc** [comment]
This is an unfortunate corner case, with a complicated history.

The file you are looking at starts as follows:

```
LOCUS       CP010426              829411 bp    DNA     circular ENV 21-SEP-2017
DEFINITION  Archaeon GW2011_AR20 chromosome, complete genome.
ACCESSION   CP010426
VERSION     CP010426.1
DBLINK      BioProject: PRJNA268032
            BioSample: SAMN03217314
KEYWORDS    ENV.
SOURCE      archaeon GW2011_AR20 (groundwater metagenome)
  ORGANISM  archaeon GW2011_AR20
            Archaea.
```

Note as typical in the NCBI GenBank files, there is a source feature later on with more taxonomic information including an NCBI taxid.

With the latest Biopython code (1.73 with changes since):

```
>>> record = SeqIO.read(handle, "genbank")
>>> for k, v in record.annotations.items():
...    print(k, v)
... 
('comment', 'RNA annotation was added by the NCBI Prokaryotic Genome Annotation\nPipeline (released 2013). Information about the Pipeline can be\nfound here: http://www.ncbi.nlm.nih.gov/genome/annotation_prok/')
('source', 'archaeon GW2011_AR20 (groundwater metagenome)')
('taxonomy', [])
('structured_comment', OrderedDict([('Genome-Assembly-Data', OrderedDict([('Assembly Method', 'idba_ud v. Oct-2011'), ('Genome Coverage', '20x'), ('Sequencing Technology', 'Illumina HiSeq')]))]))
('keywords', ['ENV'])
('references', [Reference(title='Genomic expansion of domain Archaea highlights roles for organisms from new phyla in anaerobic carbon cycling', ...), Reference(title='Direct Submission', ...)])
('accessions', ['CP010426'])
('molecule_type', 'DNA')
('data_file_division', 'ENV')
('date', '21-SEP-2017')
('organism', 'archaeon GW2011_AR20 Archaea.')
('sequence_version', 1)
('topology', 'circular')
```

And yes, in this case it does look like the taxonomy is wrongly missed. However,

https://github.com/biopython/biopython/blob/master/Bio/GenBank/Scanner.py#L1573

Sadly the old bug tracker is offline, so http://bugzilla.open-bio.org/show_bug.cgi?id=2591 is no help - but I have most of the details in old emails. It started with this GenBank entry:

```
LOCUS       NC_011147            4581797 bp    DNA     circular BCT 29-AUG-2008
DEFINITION  Salmonella enterica subsp. enterica serovar Paratyphi A str.
            AKU_12601, complete genome.
ACCESSION   NC_011147
VERSION     NC_011147.1  GI:197361212
KEYWORDS    complete genome.
SOURCE      Salmonella enterica subsp. enterica serovar Paratyphi A str.
            AKU_12601
  ORGANISM  Salmonella enterica subsp. enterica serovar Paratyphi A str.
            AKU_12601
            Bacteria; Proteobacteria; Gammaproteobacteria; Enterobacteriales;
            Enterobacteriaceae; Salmonella.
REFERENCE   1
...
```

The old Bugzilla issue 2591 was to do with line wrapping in very long taxonomic names. The discussion led to the NCBI updating the GenBank release notes on this:

https://ftp.ncbi.nih.gov/genbank/gbrel.txt

```
   ORGANISM	- Formal scientific name of the organism (first line)
and taxonomic classification levels (second and subsequent lines).
Mandatory subkeyword in all annotated entries/two or more records.

   In the event that the organism name exceeds 68 characters (80 - 13 + 1)
   in length, it will be line-wrapped and continue on a second line,
   prior to the taxonomic classification. Unfortunately, very long 
   organism names were not anticipated when the fixed-length GenBank
   flatfile format was defined in the 1980s. The possibility of linewraps
   makes the job of flatfile parsers more difficult : essentially, one
   cannot be sure that the second line is truly a classification/lineage
   unless it consists of multiple tokens, delimited by semi-colons.
   The long-term solution to this problem is to introduce an additional
   subkeyword, probably 'LINEAGE' . This might occur sometime in 2009
   or 2010.
```

Since there are no semi-colons in the second line ``            Archaea.`` it is ambiguous as a possible extension of the ``  ORGANISM  archaeon GW2011_AR20`` line (what Biopython has done, which I understood to be the recommendation) or as a taxonomy entry.

In this case the ``ORGANISM`` line is quite short (32 characters), so perhaps that could be taken into account heuristically?

There is as yet no ``LINEAGE`` line which the NCBI were originally planning to add.

**Comment by bioreps** [comment]
Thank you. So it seems like there is no elegant solution to this. I will come up with some heuristic to check if a Gbk file is from bacteria or archaea in case `taxonomy` is empty.

**Comment by peterjc** [comment]
If you're happy, that does seem to be the most pragmatic way forward (although a reminder to the NCBI about the ``LINEAGE`` idea might be worth trying). Thanks!

**Comment by bioreps** [comment]
I will flag it to NCBI :)
