### ISSUE TITLE
Codon table is out of date

### ISSUE THREAD

**Issue by Benjamin-Lee** [biopython/biopython#2080]
[`gc.prt`](ftp://ftp.ncbi.nih.gov/entrez/misc/data/gc.prt), from which the `Data/CodonTable` file is generated, now includes codon tables up to 32 (the [site](https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG33) goes up to 33, though).

Can we get it updated?

**Comment by MarkusPiotrowski** [comment]
Yes, we have a script for this. I'll have a look.

**Comment by peterjc** [comment]
Yes, we're at v4.2 of the NCBI genetic codes,

https://github.com/biopython/biopython/blob/master/Bio/Data/CodonTable.py

There have been two changes since in ftp://ftp.ncbi.nih.gov/entrez/misc/data/gc.prt
 (the computer readable file we read):

```
--  Version 4.4
--     Added GTG as start codon for genetic code 3
--     Added Balanophoraceae plastid genetic code 32
--
--  Version 4.3
--     Change to CTG -> Leu in genetic codes 27, 28, 29, 30
```

The script we use is here: https://github.com/biopython/biopython/blob/master/Scripts/update_ncbi_codon_table.py

@Benjamin-Lee would you be interested in doing this and making a pull request? Or leave it to Markus?

**Comment by MarkusPiotrowski** [comment]
I'm nearly ready with the pull request. I want to submit it together with an update of `RestrictionDictionary` so that we have updated data files for the 1.74 release.

**Comment by peterjc** [comment]
OK, thanks Markus. And thank you @Benjamin-Lee for the heads up.

Maybe we should add checking the NCBI codon tables and REBASE enzymes to our release process check list? https://biopython.org/wiki/Building_a_release

**Comment by MarkusPiotrowski** [comment]
> Maybe we should add checking the NCBI codon tables and REBASE enzymes to our release process check list? https://biopython.org/wiki/Building_a_release

Principally, yes. However, for codon tables this may need some more effort. E.g. due to changes in an older table and a new table with ambiguous stop codons, I needed to adjust the tests. Also, I always add a new test for a new codon table.
