### ISSUE TITLE
Tell flake8 to ignore top-level build directory

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2090]
Currently the contributing file suggests running:

```bash
flake8
```

In the root folder if you have previously run a build/install, this will search the build directory - which due to the way the ``per-file-ignores`` currently seem to work will mean lots of false positives.

That aside, it would also fail if the last build is older than the current ``.flake8`` settings (which typically get stricter over time).

And, it will also take roughly twice as long as really needed.

Can we include this folder in the ``per-file-ignores``?

Or, do we need to suggest something like:

```bash
flake8 Bio/ BioSQL/ Scripts/ Tests/ Doc/
```

**Comment by MarkusPiotrowski** [comment]
Maybe `CONTRIBUTING.rst` is not clear about this, it is clearer worded in `GitUsage.md` on `Biopython.org` 
Contributors should not install/run `flake8` after doing a build/install but after making a git repository and cloning Biopython. Actually, I don't think it's even neccessary to run `flake8` from the command line (except you want to work on a certain style issue), it's more important to have the pre-commit hook.
However, can't we just add the build folder to the `per-file-ignores`?
(Because I'm on Windows, I never built Biopython from scratch myself. I'm able to compile the C files manually, if I need them. Sorry for my ignorance..., I don't have a build folder in my Biopython repository)

**Comment by peterjc** [comment]
Thanks - yes, I was thinking about people working on style issues in particular, but in general I agree, the git pre-commit hook is more important.
