### ISSUE TITLE
Support individual gapped sequences for pairwise alignment

### ISSUE THREAD

**Issue by Ellmen** [biopython/biopython#2632]
Currently, the PairwiseAlignment class does not allow you to get the gapped sequences individually. This makes it hard to grab the sequences to, for instance, store them as a specified filetype.

There could be gapped_target() and gapped_query() functions that return these sequences. These functions could also be used when generating the formatted string. It would also be helpful to directly save a pairwise alignment as a fasta or something but that could wait for another ticket.

I'm happy to take a stab at this if you think it makes sense.

https://github.com/biopython/biopython/blob/master/Bio/Align/__init__.py

**Comment by mdehoon** [comment]
@Ellmen  It makes sense; I am happy to look at your proposed code. Probably it makes most sense if gapped_target and gapped_query return a string instead of a Seq object. Also, we may merge the PairwiseAlignment and MultipleSeqAlignment classes at some point, so it may be better to have a single function or attribute that takes an index (0 or 1 for now) instead of target/query.

**Comment by Ellmen** [comment]
@mdehoon great, I'll try to get to that today. I like the idea of merging the pairwise and MSA classes 👍

**Comment by mdehoon** [comment]
@Ellmen  I believe this issue has been fixed by #3565  (which is in Biopython release 1.79).  Please reopen this issue if it hasn't been solved.
