### ISSUE TITLE
Question: Test for valid FASTA/Q

### ISSUE THREAD

**Issue by ms-gx** [biopython/biopython#2691]
What is the most elegant and efficient way to test if I have a valid FASTA/Q with Biopython?

I have Biopython 1.73

**Comment by peterjc** [comment]
Note the current release is Biopython 1.76, your release is a year old. It shouldn't matter for this specific question.

Valid FASTA is a very tricky concept - the format isn't formally defined and almost anything goes - different tools have their own rules and limits on things like what letters are expected in the sequence.

FASTQ is better, but still the closest thing to a specification was something we wrote after the fact:
https://doi.org/10.1093/nar/gkp1137

Elegant and simple would be: Try parsing with ``Bio.SeqIO.parse(...)`` and if you get an error there is a problem.

With FASTA if you get no error and no records, double check the file is actually empty - it could be a non-FASTA file. This is deliberate to handle widely used things with a free format header preceding FASTA sequences, e.g. GFF format explicitly supports this.

If you want efficient, then rather than the top level ``Bio.SeqIO.parse(...)`` use the underlying string based parsers ``Bio.SeqIO.QualityIO.FastqGeneralIterator``  and ``Bio.SeqIO.FastaIO.SimpleFastaParser``, see e.g. https://www.open-bio.org/2009/09/25/biopython-fast-fastq/

**Comment by ms-gx** [comment]
Yes, I think it does the trick. Thanks!
