### ISSUE TITLE
Keep TER lines inside a chain

### ISSUE THREAD

**Issue by MauriceKarrenbrock** [biopython/biopython#2733]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0]

CPython
Linux-5.3.0-28-generic-x86_64-with-debian-buster-sid

1.77.dev0

```
### Expected behaviour

Some MD programs like Gromacs rely on TER lines that are inside a chain to distinguish the different molecules that compose them (like the protein in chain A from a ligand in chain A from a metallic ion in chain A etc...). (In fact many of the structures in the wwPDB database have them)

So if I parse a PDB file that has all the needed TER lines with Biopython and then write it on a new file it would be useful if this TER lines would be kept

### Actual behaviour

But this doesn't happen, the only TER line that remains is the one at the end of the chain

```
grep "TER " 5aol_before_biopython.pdb

TER    1713      THR A 312
TER    3426      THR B 312
TER    3441       ZN A1300
TER    3443       ZN B1300
TER    3735      HOH A2291
TER    3999      HOH B2263
```

```
grep "TER " 5aol_after_biopython.pdb

TER    2018      HOH A2291                                                       
TER    3994      HOH B2263  
```
### Steps to reproduce

```
import Bio.PDB

p = Bio.PDB.PDBParser()
struct = p.get_structure('5aol', '5aol_before_biopython.pdb')

s = Bio.PDB.PDBIO()
s.set_structure(struct)
s.save('5aol_after_biopython.pdb')
```

both pdb files are attached as txt files
[5aol_after_biopython.txt](https://github.com/biopython/biopython/files/4225590/5aol_after_biopython.txt)
[5aol_before_biopython.txt](https://github.com/biopython/biopython/files/4225591/5aol_before_biopython.txt)

### Possible patch

I am fair new to programming so I don't know if it could work but an idea could be to give a boolean is_TER variable to all atoms that is False for default and becomes True only if this atom had a TER line after it.
In this way the save() function could check for it and write an extra TER line if is_TER == True

Could it be an idea? Or otherwise how could it be done?

ps it would be very useful if this TER lines would be added even when the input file is a mmCIF and the output is still a PDB, the TER line should appear any time `_atom_site.label_asym_id` changes as usually it changes any time a different molecule is met inside the same chain

**Comment by JoaoRodrigues** [comment]
Thank you for the detailed report! I'll have a look at it in the next couple of days.

**Comment by JoaoRodrigues** [comment]
Hi @MauriceKarrenbrock 

Since the chains in the HETATM section of your example PDB are interleaved (A B A), and the OpenMM PDBWriter is overzealous about TER statements, it writes a bunch of them where they are not strictly necessary. If you look at the deposited `5aol` file on RCSB PDB, it does not have any TER statements in the HETATM section.

The specifications of the PDB format for TER statements say;

>The TER records occur in the coordinate section of the entry, and indicate the last residue presented for each polypeptide and/or nucleic acid chain for which there are determined coordinates. For proteins, the residue defined on the TER record is the carboxy-terminal residue; for nucleic acids it is the 3'-terminal residue.

My interpretation of this text is that TER statements should be added only when you have a break in the sequence of standard polypeptide and/or nucleic acid chains. HETATMs do not fall under this category. I know that some programs use TER statements to indicate gaps in the sequence as well, so I think we could consider adding TER statements where there is a non-contiguous chain (e,g. A1A2 TER A4A5 ...) but otherwise, I believe our writer is doing the right thing.

I will, however, make a patch to place TER statements after the last ATOM record, thanks for bringing that to our attention!

**Comment by MauriceKarrenbrock** [comment]
Hello! Thank you for the quick feedback!

I see what you mean and I agree.

> I will, however, make a patch to place TER statements after the last ATOM record, thanks for bringing that to our attention!

This would be great and I think it should stop Gromacs from complaining (when it will be done I'll check as fast as possible).

> I think we could consider adding TER statements where there is a non-contiguous chain (e,g. A1A2 TER A4A5 ...)

I am not sure I got what you mean here, but if you mean adding a TER when there is a missing residue I think it would confuse all the programs that complete the protein structures adding missing atoms and residues (openmm's pdbfixer for example adds a terminal oxygen anytime there is a TER line after an amino acid residue)

Thank you very very much and have a nice day!
