### ISSUE TITLE
Writing TER records with PDBIO

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#2736]
Opening an issue to discuss the placement of TER records in PDB files written by `PDBIO`, derived from #2733.

The current behavior of `PDBIO` is to write TER records at the end of all atoms of a chain, HETATM inclusive. The PDB format specs state that TER records must follow the last polypeptide/nucleic acid residue in a chain (and they never mention HETATMs).

The current implementation iterates over the residue list from `chain.get_unpacked_list`, which includes both ATOM and HETATM records. Adding a comparison to check when we find the first HETATM is not a good solution because some HETATMs are modified residues that are connected to the previous residue and so should not trigger a chain termination. The simplest approach I can think of it to use our KDTree module to check, when we find a HETATM, if it is connected to the previous residue (using a simple distance cutoff to any atom should suffice). This does make things potentially slower for structures with a lot of HETATM records but should be robust enough.

Any comments or other suggestions? @jgreener64 @peterjc

**Comment by peterjc** [comment]
Might be worth examining some PDB examples to confirm the expected behaviour, or emailing for clarification to the specification?

**Comment by jgreener64** [comment]
Sounds like a good idea. I don't use TER records much so I don't have strong opinions, but matching the PDB seems like the right thing to do. I would lean against having TER records for internal chain breaks (i.e. missing residues) because semantically I think a TER means the carboxy terminal/3' terminal ends of a protein/DNA chain, which is not relevant to missing residues.

**Comment by rob-miller** [comment]
I think that adding a flag at the input layer as suggested in #2733 would be preferable in the general case.

- For PDB input this should be easy to implement, much faster to execute, extremely robust and obvious to the user how to adjust without resorting to documentation.

- I am a dinosaur, so don't know the correct approach to assign the TER atom when reading mmCIF or other formats.  If there is not a clear way to read it from the input, then falling back to kdtree sounds reasonable.  Some thoughts:
-- I'm not comfortable with a dependency on kdtree, as it seems like a lot of complexity and doing structure analysis / determining 'meaning' at a level which should be just file parsing and I/O.  Nonetheless, I see that tracking backbone connectivity for more than a single modified residue any other way would be a nightmare.
-- it would be nice if someone would update the kdtree documentation, as bio.kdtree says it is deprecated in favor of bio.pdb.kdtrees, but this has no API documentation.
-- my preference would be to expose any distance cutoff to the user for adjustment.  As @JoaoRodrigues knows, in the code I've submitted there's a similar MaxPeptideBond setting and my vote would be to have just one setting somewhere. 
-- Adding the feature at the input level for each file format can be done incrementally, e.g. PDB first and any others that it is clear for, then on output write a TER record when the flag is found OR at the end of reading the end of the residue list as currently implemented. 

- I feel that this should be determined at the input level and available in the data sructure regardless of the method; at the very least the detail may be of use to (future) applications other than writing PDB output.  
-- My own style would be to use `hasattr()` to test for the flag when needed rather than clutter up the data structure for all the other atoms (e.g. as one would view in a debugger). 


I also feel that putting TERs at every chain break would be undesirable and not in accordance with the PDB spec - although it occurs to me that every PDB file with missing C-terminal residues does exactly this.

**Comment by JoaoRodrigues** [comment]
Thanks for the answers and feedback!

The PDB format explicitly states that TER records are to be put when a chain _terminates_. Some tools extend this and add TER records when there is a break in connectivity. It would be simple to just put a TER record when PDBIO finishes writing a chain, but this will give weird results when there are HETATM like `MSE` that follow allow the regular chain. Thus my suggestion of the connectivity check, which I agree is very sub-optimal but it's the robust solution.

Addressing @rob-miller's suggestions: setting a module-level or global parameter for connectivity is not ideal either because it depends on the molecular type. Also, reading mmCIF or other formats does not matter in principle. This is only a 'feature' of writing PDBs.

I'll try to come up with something reasonable. It's very annoying because there is no consensus on these rules...

**Comment by rob-miller** [comment]
> This is only a 'feature' of writing PDBs.

I agree the specific case of writing TER records is relevant only to PDBs, but there seems like a more general issue of how to know where the covalently bonded chain ends when processing SMCRA structures?  I ignore this problem by limiting to 20 natural AAs, but I wonder why it has not been raised before.

**Comment by MauriceKarrenbrock** [comment]
Sorry if I am interfering, but I noticed that if you convert a pdb to a mmcif only containing natural AA (I used 5aol) the `label_asym_id` (that could be considered the most similar thing to a TER record) is written correctly. But it doesn't look like it would work with a not natural AA (that starts with HETATM) (but I have no example to make a test).

in fact in the [mmcifio.py](https://github.com/biopython/biopython/blob/master/Bio/PDB/mmcifio.py) file lines 315 - 324 is : 

>                     # Check if the molecule changes within the chain
>                     # This will always increment for the first residue in a
>                     # chain due to the starting values above
>                     if residue_type != prev_residue_type or (
>                         residue_type == "HETATM" and resname != prev_resname
>                     ):
>                         entity_id += 1
>                     prev_residue_type = residue_type
>                     prev_resname = resname
>                     label_asym_id = self._get_label_asym_id(entity_id)

So I guess that a fast patch for pdb files would be to put a similar "if", something like:
```
if residue_type == "HETATM" and  prev_residue_type == "ATOM":
    # PRINT TER LINE
```
But the not natural AA would still be a problem for both mmcif and pdb files

And I agree with @rob-miller about the fact that it would be very useful in general to be able to know where a covalently bonded molecule begins and ends by checking the Biopython structure aside from the kind of file the structure was taken from.

I hope I didn't disturb, and have a nice day.

**Comment by JoaoRodrigues** [comment]
Since the documentation and format specification is quite ambiguous, to avoid introducing expensive calculations, I think it's better to leave things as they are.
