### ISSUE TITLE
Bio.bgzf.BgzfWriter splits lines between blocks

### ISSUE THREAD

**Issue by MatthewRalston** [biopython/biopython#2771]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>import sys; print(sys.version)
3.7.4 (default, Oct 25 2019 ...)
[GCC 9.2.0]
>import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.3.7-arch1-1-ARCH-x86-64-with-arch
>import Bio; print(Bio.__version__)
1.74
```

### Expected behaviour

I expect the `write` method in `bgzf.BgzfWriter.write()` to not split a new line of `data` between blocks. More specifically, I am calling `bgzfout.write` like I would do do print a line of data (like a read) to the bgzf filehandle. Although the [first part of the conditional](https://github.com/biopython/biopython/blob/master/Bio/bgzf.py#L830) will restrict appends if the new data and the current buffer are less than 65536, EVENTUALLY the else statement is triggered with some amount of data preceding the split at 65536 and some following the split. If instead, the `_buffer` were scanned backwards for a newline character, the rest of the preceding text following that newline could be the first elements of the new buffer. But instead, the magic 65536 is used to split lines of text being appended to the buffer.

### Actual behaviour

`BgzfWriter.write` as written will take the first 65535 and pass those to _write_block. However, if that includes part of the new line i.e. `data`, then **the new line will be split between sequential blocks,** which will invalidate nearly any bgzf file that is using the write method to write lines of data expecting that not every block is necessarily packed to 65536 but instead is as close as possible while retaining the order of data on each line. 

I can imagine a case where instead the newline should not be the deciding factor. Most users will be writing plain ASCII text to bgzf files or will not have each block measured out before hand and rely on the write method to properly delineate (no pun intended).

### Steps to reproduce

Write the following to a bgzf file, and the first break should occur at line 7788. (near the bottom of the pastebin).

```
7786    134
7787    74
7788
...... new block ......
    59
7789    48
```

https://pastebin.com/YLZAyyAT

**Comment by peterjc** [comment]
I don't understand what your issue is asking. Do you think you have found a bug, or just a design choice you disagree with?

Assuming you are dealing with text files, there is no reason to assume a line of text will be entirely within a single block - it can be split over a block boundary.

As I recall the samtool library does not always write a full block, sometimes opting to finish a block early to avoid splitting a record between two blocks. But this is purely an optimisation - either way should be fine.

**Comment by MatthewRalston** [comment]
Yes sir,
It was asking why the default behavior of bgzf is to split a line of text between two blocks, since the readline scans the current `_buffer` for the next newline character. If the next newline character isn't available (i.e. its in the following block), is that considered undesirable behavior.

As I recall, SAM files are also plaintext? I'm attaching [a link to the samtools spec](https://samtools.github.io/hts-specs/SAMv1.pdf). As I understand the code, the input to the write function is *expected* to be `str`. Maybe I'm not understanding your frustration?

I am questioning whether it is necessary to split a single line of text between two blocks by default. It doesn't seem like a changed behavior here would conflict with bgzf specification, and it would make each block actually independent.

**Comment by peterjc** [comment]
SAM files are plain text, but are not used with BGZF. Instead a more compact binary format is used within BGZF giving a BAM file (B for binary). However, plain text files are used with BGZF in the related tabix tool. And in Biopython SeqIO, see https://blastedbio.blogspot.com/2011/11/bgzf-blocked-bigger-better-gzip.html

We *have* to look for a newline in ``.readline()`` because that's what Python's ``.readline()`` does - it reads the next _line_ of text.

On the other hand, ``.write()`` is not necessarily line based. It could be one byte, a whole paragraph, 1MB, or even an entire file of content in one go.

The block writing behaviour follows the early versions of samtools (the de facto reference implementation for BGZF) and writes full blocks, regardless of any potential logical splits (like line breaks or records). IIRC, later versions of samtools would write nearly full BGZF blocks if this avoided splitting a record between two blocks. This was a tiny optimisation for later reading back data.

If you want to do something similar in your code, call the ``.flush()`` method which will finish the current block (but don't do this too often, you will get lots of small blocks and the compression level will suffer):
https://github.com/biopython/biopython/blob/biopython-176/Bio/bgzf.py#L818

**Comment by MatthewRalston** [comment]
Hey @peterjc , I started something interesting as a result from this issue, its a new file format in bgzf and it all started because you helped my curiosity about bgzf! Thank you for being a good and responsive developer, you inspire us all!

https://matthewralston.github.io/kmerdb

**Comment by peterjc** [comment]
Thanks for sharing @MatthewRalston - I see you've written plenty of documentation and use case motivating blog posts too. You're also setting a great example 👍
