### ISSUE TITLE
Return element in atom.get_full_id() ?

### ISSUE THREAD

**Issue by martinfalk** [biopython/biopython#2860]
Is there a reason why `atom.get_full_id()` does not return the actual element? I know that you can access the element via `atom.element` but I find it a bit strange that the full ID does not know about it.
 
https://github.com/biopython/biopython/blob/6c75d2da18afdc89b6b3ef994d87c601f856ae27/Bio/PDB/Atom.py#L365-L371

**Comment by jgreener64** [comment]
I guess because the element isn't used to distinguish between different atoms in an identification sense, whereas all the other properties there are.

So if you copied an atom and changed any one of the 6 values it could exist happily (provided the relevant parents exist).

But if you copied an atom and changed only its element then Biopython would get confused as there is no way to access the atom uniquely in the hierarchical manner (`struc[mod][chain][res][atom]`).

**Comment by martinfalk** [comment]
OK, that sounds like a reasonable explanation. Thanks.

**Comment by JoaoRodrigues** [comment]
Adding to (or more reinforcing) what @jgreener64 said, an element does not add much to uniquely identify an atom. You cannot have an alpha carbon with different elements. The `full_id` is used for identification, so it includes only the properties that can do that.

**Comment by peterjc** [comment]
Can we close this - or is this a sign the documentation could be improved? e.g. the Atom's get_full_id docstring?

**Comment by JoaoRodrigues** [comment]
Indeed, just pushed a small edit to the docstring. But I'll go ahead and close this issue.
