### ISSUE TITLE
Biopython pairwise sequence alignment behavior change between 1.59 and 1.8

### ISSUE THREAD

**Issue by michelsanner** [biopython/biopython#3303]
### Setup

I am reporting a problem with Biopython 1.8, Python version 3.7 , and operating
system as follows:

3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0]
CPython
Linux-4.9.0-11-amd64-x86_64-with-debian-9.12
1.79.dev0

### Expected behaviour
running the following code 
from Bio import pairwise2
aln = pairwise2.align.globalxx('EPQYEEIPIYL', 'EPQ?EEIPIYL', one_alignment_only=True)[0]
print(aln)

produced the desired alignment in 1.59:
('EPQYEEIPIYL', 'EPQ?EEIPIYL', 10.0, 0, 11)

while in 1.7X I am getting a spurious insertion

('EPQY-EEIPIYL', 'EPQ-?EEIPIYL', 10.0, 0, 12)

I feel like the old behavior is better

Thanks

**Comment by MarkusPiotrowski** [comment]
Dear @michelsanner, thank you very much for your comment. 

The aim of a pairwise alignment algorithm is to achieve an alignment with the best score (or the least costs). From the view of the algorithm (here Needleman-Wunsch-Gotoh) the situation "one gap in seqA followed by one gap in seqB" is not forbidden. The fact that the older implementation of this algorithm in Biopython's `pairwise2` did not allow this, was a shortcoming and was criticized e.g. in this [paper](https://doi.org/10.1101/031500). That was the reason for re-writing `pairwise2` for Biopython 1.68 (in 2016) (with the side effect, however, unrelated to the original issue, of increased performance regarding speed and memory usage). As you see, the alignment with the "spurious insertion" in your example has the same score as the other one, and in fact, the other alignment is also produced (would have index `[1]`).

This behavior is documented in the docstring of the module which can be read in our [API documentation](https://biopython.org/docs/latest/api/Bio.pairwise2.html), in detail:
```
Depending on the penalties, a gap in one sequence may be followed by a gap in the other sequence.
If you don’t like this behaviour, increase the gap-open penalty:

>>> for a in pairwise2.align.globalms("A", "T", 5, -4, -1, -.1):
    print(format_alignment(*a))

A-

-T
  Score=-2

>>> for a in pairwise2.align.globalms("A", "T", 5, -4, -3, -.1):
    print(format_alignment(*a))
A
.
T
  Score=-4
```

This also explains how you can prevent this: by increasing the gap penalty (two gaps should be more expensive than one mismatch). In fact, that is what most "standard settings" in alignment programs do. 

Your example shows an amino acid alignment and I doubt that `globalxx` comes close to meaningful alignments in such cases (with 'real' proteins). You might consider using a substitution matrix:
```python
>>> from Bio import pairwise2 as pw
>>> from Bio.Align import substitution_matrices

Warning (from warnings module): ...

>>> blosum62 = substitution_matrices.load("BLOSUM62")
>>> aln = pw.align.globalds("EPQYEEIPIYL", "EPQ*EEIPIYL", blosum62, -10, -0.5)[0]  # replacing your ? with a * which is in the matrix
>>> print(pw.format_alignment(*aln))
EPQYEEIPIYL
|||.|||||||
EPQ*EEIPIYL
  Score=49
```

Alternatively, if you want to keep the simple matching scheme, use `globalms`  to set different gap parameters:
```python
>>> aln = pw.align.globalms("EPQYEEIPIYL", "EPQ?EEIPIYL", 1, -1, -2, -.5)[0]
# identical to: aln = pw.align.globalms("EPQYEEIPIYL", "EPQ?EEIPIYL", match=1, mismatch=-1, open=-2, extend=-.5)[0]
>>> print(pw.format_alignment(*aln))
EPQYEEIPIYL
|||.|||||||
EPQ?EEIPIYL
  Score=9
```


Finally, if you are doing many pairwise alignments, you should consider using our new [`PairwiseAligner`](http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec100) which has a much better performance and other advantages (the latter because it is implemented as a class).

**Comment by peterjc** [comment]
Note there was no Biopython 1.8, from the text it looks like you mean the current master branch - what will become Biopython 1.79 at some point.

**Comment by michelsanner** [comment]
Hello Peter.
Yes I got the arc of the latest version ftom GitHub and it is 1.79
-Michel

On Oct 9, 2020, at 4:48 AM, Peter Cock <notifications@github.com<mailto:notifications@github.com>> wrote:


Note there was no Biopython 1.8, from the text it looks like you mean the current master branch - what will become Biopython 1.79 at some point.

**Comment by MarkusPiotrowski** [comment]
@michelsanner Can we close this?

**Comment by michelsanner** [comment]
Yes. Thanks

On Oct 15, 2020, at 5:26 AM, Markus Piotrowski <notifications@github.com<mailto:notifications@github.com>> wrote:


@michelsanner<https://github.com/michelsanner> Can we close this?

**Comment by MarkusPiotrowski** [comment]
Thank you!
