### ISSUE TITLE
Potential bug with pairwise2.align.globalms when using 0 as a gap

### ISSUE THREAD

**Issue by Darhal** [biopython/biopython#3453]
### Setup
I am reporting a problem with Biopython version, Python version, and operating
system as follows:
```
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]
CPython
Windows-10-10.0.19041-SP0
1.78
```
### Expected behaviour
I'm trying to find the optimal global alignment between these two sequences: `GAAT` and `GGAT`
with the following parameters: match = 1, mismatch = 0 and gap = 0.

I'm expecting an array of 6 optimal alignments like this (the third element is the score):
```
['GAAT', 'GGAT', 3]  
['-GAAT', 'GGA-T', 3]
['-GAAT', 'GG-AT', 3]
['GA-AT', 'G-GAT', 3]
['G-AAT', 'GGA-T', 3]
['G-AAT', 'GG-AT', 3] <- the problem is here (this is missing when using 'pairwise2.align.globalms')
```

### Actual behaviour
The actual output I'm getting is 5 optimal alignments using the `pairwise2.align.globalms` (see the code below):
```
['GA-AT', 'G-GAT', 3]
['GAAT', 'GGAT', 3] 
['-GAAT', 'GG-AT', 3]
['G-AAT', 'GGA-T', 3]
['-GAAT', 'GGA-T', 3]
```
The following is missing in the output above: `['G-AAT', 'GG-AT', 3]`
I'm also getting the same behaviour using `pairwise2.align.globalxx("GAAT", "GGAT")`

### Steps to reproduce
The actual code I'm running is the following:
```python
from Bio import pairwise2
alignments = pairwise2.align.globalms("GAAT", "GGAT", 1, 0, 0, 0)
formated_alignments = [ [ a[0], a[1], int(a[2]) ] for a in alignments ]
for l in formated_alignments:
    print(l)
```

### More informations
I used [this ](http://rna.informatik.uni-freiburg.de/Teaching/index.jsp?toolName=Needleman-Wunsch) calculator online that uses the NW algorithm to cross check the output with BioPython and my own NW Implementation. My implementation and the online calculator output matches, but they don't match with BioPython that is missing one optimal alignment as mentioned above.
I also tried with different sequences with gaps that are not equal to 0 and all the outputs from the different implementations matched (so the problem happens when the gap is 0).
This could be a bug or maybe I'm missing something. I would be thankful if someone tries to clarify why the outputs I'm getting doesn't match with BioPython one.

**Comment by mdehoon** [comment]
The newer pairwise aligner in Biopython gives the expected result:
```python
>>> from Bio.Align import PairwiseAligner
>>> aligner = PairwiseAligner()
>>> print(aligner)
Pairwise sequence aligner with parameters
  match_score: 1.000000
  mismatch_score: 0.000000
  target_internal_open_gap_score: 0.000000
  target_internal_extend_gap_score: 0.000000
  target_left_open_gap_score: 0.000000
  target_left_extend_gap_score: 0.000000
  target_right_open_gap_score: 0.000000
  target_right_extend_gap_score: 0.000000
  query_internal_open_gap_score: 0.000000
  query_internal_extend_gap_score: 0.000000
  query_left_open_gap_score: 0.000000
  query_left_extend_gap_score: 0.000000
  query_right_open_gap_score: 0.000000
  query_right_extend_gap_score: 0.000000
  mode: global

>>> alignments = aligner.align("GAAT", "GGAT")
>>> len(alignments)
6
>>> for alignment in alignments:
...     print(alignment)
... 
G-AAT
|-|-|
GGA-T

-GAAT
-||-|
GGA-T

GA-AT
|--||
G-GAT

G-AAT
|--||
GG-AT

-GAAT
-|-||
GG-AT

GAAT
|.||
GGAT

>>> ```

**Comment by Darhal** [comment]
Thanks @mdehoon that works fine! But I have one more question is `pairwise2.align.globaldx` (calculate the alignment using cost matrix) bogus too ? if so what's the alternatives and is there a way to pass in the gap penalty along with the cost matrix ?

**Comment by MarkusPiotrowski** [comment]
@Darhal The result that you are missing is already present in your 4th alignment:

```
Your 4th Aligment:
GA-AT
G-GAT

'Missing' Alignment:
G-AAT
GG-AT
```
You see that both the A in seq1 and the G in seq2 are paired with a gap.
You can reduce the problem to the alignment of 'A' to 'G'. With your parameters it will be:
```
G
A

G-
-A

-G
A-
```

Of the two possibilities of 'gap in one sequence followed by a gap in the other sequence', `pairwise2` will only report one, because they are considered redundant. (Also, many alignment programs even do not allow alignments of this type). 
This behavior is documented in the code: https://github.com/biopython/biopython/blob/7b09da61fa9e959fd4c90fa9ee3772861f2979e6/Bio/pairwise2.py#L968-L971

I can understand that this confuses you, but in 'real world' alignments I'd prefer to return more different 'meaningful' alignments instead of numerous alignments that differ only in the sequence of these two gaps. The reason behind this is that `pairwise2` will only return a maximum of 1000 alignments and with longer sequences (and the alignment parameters that allow such results) you would get many of such 'redundant' alignments.

So 'bogus' is not the correct term to describe the behavior of `pairwise2` here. By the way, when you have written your own NW calculator you possibly know that the placement of gaps is not only dependent on the cost of gaps but also on the cost of mismatches. If opening two gaps is more expensive than one mismatch, you will not get the results where a deletion is directly followed by an insertion (or the other way round). Actually, this is the case for 'usual' standard settings in most sequence editor programs.

**Comment by MarkusPiotrowski** [comment]
Regarding the question of how to pass gap penalties with a matrix: use `globalds`.
https://github.com/biopython/biopython/blob/7b09da61fa9e959fd4c90fa9ee3772861f2979e6/Bio/pairwise2.py#L37-L54

Also: https://github.com/biopython/biopython/blob/7b09da61fa9e959fd4c90fa9ee3772861f2979e6/Bio/pairwise2.py#L265-L267

**Comment by Darhal** [comment]
@MarkusPiotrowski I actually completely missed that! Thanks a lot for the detailed answer.
