### ISSUE TITLE
ImportError: cannot import name '_aligners' from 'Bio'

### ISSUE THREAD

**Issue by muwaful** [biopython/biopython#3535]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
CPython
Windows-10-10.0.19041-SP0
1.78

### Expected behavior

to import normally
I'm sorry I'm a student working with genomes with little coding knowledge. I've looked at many posts online, and I can't seem to resolve this. I've tried uninstalling and reinstall pip to make sure it is installed in the correlated/correct biopython. I'm lost at this point, and I don't know how to solve this. Thank you so much in advance for your help!

### Actual behavior

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-66-5d24a7c49c42> in <module>
----> 1 from Bio import SeqIO

c:\users\abdul\appdata\local\programs\python\python39\lib\site-packages\Bio\SeqIO\__init__.py in <module>
    380 from Bio.File import as_handle
    381 from Bio.SeqRecord import SeqRecord
--> 382 from Bio.Align import MultipleSeqAlignment
    383 
    384 from Bio.SeqIO import AbiIO

c:\users\abdul\appdata\local\programs\python\python39\lib\site-packages\Bio\Align\__init__.py in <module>
     18 
     19 from Bio import BiopythonDeprecationWarning
---> 20 from Bio import _aligners
     21 from Bio.Align import substitution_matrices
     22 from Bio.Seq import Seq

ImportError: cannot import name '_aligners' from 'Bio' (c:\users\abdul\appdata\local\programs\python\python39\lib\site-packages\Bio\__init__.py)

### Steps to reproduce

from Bio import SeqIO

**Comment by mdehoon** [comment]
How  did you install biopython?

**Comment by muwaful** [comment]
I actually had a ton of trouble installing biopython. As usual I tried pip install biopython; however this raised many errors and did not install. So, by surfing the web, I installed anaconda and did conda install biopython, which worked. This allowed me to use the package Bio.Entrez (from Bio import Entrez). Now, however, I need to use SeqIO (from Bio import SeqIO), which isn't working of course :(

**Comment by peterjc** [comment]
You quite possibly have multiple copies of Python and Biopython on your machine, some with and some without the C code, etc. If you were not using Python for anything else, I strongly suggest you uninstall all the other Pythons except the one from anaconda.

**Comment by mdehoon** [comment]
The surprising part is in
```
c:\users\abdul\appdata\local\programs\python\python39\lib\site-packages\Bio\Align_init_.py in
18
19 from Bio import BiopythonDeprecationWarning
---> 20 from Bio import _aligners
21 from Bio.Align import substitution_matrices
22 from Bio.Seq import Seq

```

On line 20 of `Bio/Align/__init__.py`, the code in Biopython 1.78 is `from Bio.Align import _aligners`, not `from Bio import _aligners`. WHen you install biopython with conda, do you get any notification exactly which version is being installed?

**Comment by mdehoon** [comment]
@muwaful  Any updates? I am really wondering how this line of code that is not in the official Biopython release found its way into the conda distribution.

**Comment by MarkusPiotrowski** [comment]
The reason for the ton of problems when installing Biopython on Win10 with Python 3.9 is that we don't have the proper wheel for Python 3.9 on Windows. 
Thus doing `pip install biopython` downloads the uncompiled source and then tries to compile it, which usually fails because of a non-existing C compiler on Windows.
This happened also to me.

I guess in your case you have now several/mixed installations. When using Conda you also need to activate the Conda environment. Looking at your path, it seems that you/your system is actually _not_ using the Conda installation, where I would expect the folder 'conda' in the path.

@peterjc Is there a simple way to tell `pip` not to install on Windows when the Python version is > 3.8?

**Comment by peterjc** [comment]
Perhaps a simple fix is to release a Python 3.9 wheel for the last release (with any essential fix for Python 3.9 backported if required)?

Or we hurry up the new release (our volunteer had something come up last month).

**Comment by peterjc** [comment]
I see conda-forge does not have Python 3.9 packages for Biopython https://anaconda.org/conda-forge/biopython/files yet either, that might be simple to rectify

**Comment by peterjc** [comment]
Correcting myself: conda-forge already had Python 3.9 packages for Biopython 1.78 since the start of March:

https://anaconda.org/conda-forge/biopython/files
https://github.com/conda-forge/biopython-feedstock/pull/29

**Comment by peterjc** [comment]
Biopython 1.78 Windows and macOS compiled wheels for Python 3.9 done and on PyPI now:

* biopython-1.78-cp39-cp39-macosx_10_9_x86_64.whl
* biopython-1.78-cp39-cp39-win_amd64.whl
* biopython-1.78-cp39-cp39-win32.whl

There is at least one known issue under Python 3.9 which has been fixed since (#2773).

This has flagged an annoyance with the wheel building which we would have hit soon anyway with Biopython 1.79, see recent commits on https://github.com/biopython/biopython-wheels and https://github.com/biopython/biopython-wheels/issues/8

**Comment by peterjc** [comment]
@muwaful The suggestion from Markus that an attempt to install Biopython under Python 3.9 on Windows failed at the compilation stage (we have some C code) might explain some of the behaviour on your system.

If you can start from a clean machine (uninstall/delete all the failed Biopython stuff - or even remove and reinstall the entire anaconda provided Python 3.9), then either ``conda install biopython`` or ``pip install biopython`` should now be able to fetch a pre-compiled Biopython 1.78 and just work.

**Comment by muwaful** [comment]
I'm very sorry for the late reply! I want to thank everyone sincerely! I uninstalled every version of pip, anaconda, and python; then, I reinstalled python and pip (did not install anaconda). I then installed pip and biopython, and everything seems to work now. Thank you so much!

**Comment by peterjc** [comment]
Thank you for letting us know, and thank you for your patience in helping solve this.
