### ISSUE TITLE
Bio.Entez parser, NLM Catalog missing DTD

### ISSUE THREAD

**Issue by jzstoller** [biopython/biopython#354]
Can the "NLMCatalogRecordSet DTD (01/01/14)" be added?

see http://www.nlm.nih.gov/databases/dtd/

**Comment by buhtz** [comment]
@jzstoller Did you get an answer from NCBI?

**Comment by peterjc** [comment]
XML can use a DTD file to specify what fields are going to be present etc. Most of the NCBI databases offering XML format support this, so the ``Bio.Entrez`` parser was built to expect this by default (``validate=True``).

You can try turning off the DTD validation with ``Entrez.read(handle, validate=False)``.

**Comment by buhtz** [comment]
This result in an error from expat.

**Comment by peterjc** [comment]
You might as well post the exception and traceback here, it would help anyone searching for it later.

Other than emailing the NCBI, your best bet for this particular flavour of NCBI XML would be to switch to a non-DTD based XML parser - e.g. using ElementTree directly (included in the Python standard library).

**Comment by mdehoon** [comment]
Entrez.read(handle, validate=False) does work correctly:

```python
>>> from Bio import Entrez
>>> h = Entrez.efetch(db='nlmcatalog', id='7508686', retmode='xml')
>>> Entrez.read(h, validate=False)
''
```
but since there is no DTD, the record is empty. I would suggest to contact NCBI about this.

**Comment by lennax** [comment]
I received the following response from the NCBI:

"The National Library of Medicine (NLM) distributes XML data for LocatorPlus,
which is the same resource as the NLM Catalog:
https://www.nlm.nih.gov/databases/leased_tsd_xml.html
 
XML output for the NLM Catalog did not have a DTD specification because
the XML was a combination of multiple XMLs."

As a workaround, I manually inserted a doctype specification:

    <!DOCTYPE NLMCatalogRecordSet PUBLIC "NLM Catalog" "http://www.nlm.nih.gov/databases/dtd/nlmcatalogrecordset_150101.dtd">

into the saved XML file (created by writing `h.read()` to a file) and then Entrez could read it. It is not ideal, but in cases where it is known that the doctype is missing, this will allow the data to be parsed.

Is it possible to have Entrez provide a more specific error message if the doctype line is missing (i.e. specify that it is not a Biopython error)?

**Comment by buhtz** [comment]
So there is another alternative database for NLM-catalog? Didn't understand the text behind the mail-link.
