### ISSUE TITLE
Failure to parse origin-spanning features

### ISSUE THREAD

**Issue by jakebeal** [biopython/biopython#3746]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.9.6 (default, Jun 29 2021, 06:20:32) 
[Clang 12.0.0 (clang-1200.0.32.29)]
CPython
macOS-10.15.7-x86_64-i386-64bit
1.79
```

### Expected vs. Actual behaviour

Loading the attached GenBank file (renamed for upload to GitHub): [pME_B_0_08_0005_Akan(Vn)_(sfgfp).gb.txt](https://github.com/biopython/biopython/files/7210096/pME_B_0_08_0005_Akan.Vn._.sfgfp.gb.txt)
discards the origin-spanning feature as being from an undefined sequence topology, despite the fact that sequence topology is recognized as circular.

### Steps to reproduce

````
> records = [r for r in SeqIO.parse('pME_B_0_08_0005_Akan(Vn)_(sfgfp).gb','gb')]
/usr/local/lib/python3.9/site-packages/Bio/GenBank/__init__.py:352: BiopythonParserWarning: It appears that '3093..570' is a feature that spans the origin, but the sequence topology is undefined. Skipping feature.
  warnings.warn(
> records[0].annotations
{'topology': 'circular', 'data_file_division': 'UNK', 'date': '22-SEP-2021', 'accessions': ['urn.local...ef-c2dp9c9'], 'keywords': [''], 'source': '', 'organism': '.', 'taxonomy': [], 'molecule_type': 'DNA'}
````

**Comment by peterjc** [comment]
The problem is here:

https://github.com/biopython/biopython/blob/biopython-179/Bio/GenBank/__init__.py#L351

```python
    if int(s_pos) > int(e_pos):
        if seq_type is None or "circular" not in seq_type.lower():
            warnings.warn(
                "It appears that %r is a feature that spans "
                "the origin, but the sequence topology is "
                "undefined. Skipping feature." % loc_str,
                BiopythonParserWarning,
            )
            return None
        warnings.warn(
            "Attempting to fix invalid location %r as "
            "it looks like incorrect origin wrapping. "
            "Please fix input file, this could have "
            "unintended behavior." % loc_str,
            BiopythonParserWarning,
        )
        ...
```

The topology check via ``seq_type`` will only work on old style GenBank files. In your case that if-condition should not have triggered - you should have seen the "Attempting to fix invalid location" warning instead (and hopefully it would have fixed it).

**Comment by starling13** [comment]
I'v discovered related issue, trying to manipulate genbank [file](https://media.addgene.org/snapgene-media/v1.7.9-0-g88a3305/sequences/180430/7ebfcf46-ecea-495d-a556-b75fdbee79b5/addgene-plasmid-11664-sequence-180430.gbk) with linear DNA and overlapping features.
This branch
```python
if seq_type is None or "circular" not in seq_type.lower():
    warnings.warn(
     "It appears that %r is a feature that spans "
    "the origin, but the sequence topology is "
    "undefined. Skipping feature." % loc_str,
    BiopythonParserWarning,
)
return None
```
leaves feature with 'None ' as feature location. Feature debug print is
```
type: enhancer
location: None
qualifiers:
    Key: label, Value: ['CMV enhancer']
    Key: note, Value: ['human cytomegalovirus immediate early enhancer']
```
Then, `record.format('genbank')` produces exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/biopython-1.80.dev0-py3.7-linux-x86_64.egg/Bio/SeqIO/InsdcIO.py", line 324, in _insdc_location_string
    parts = location.parts
AttributeError: 'NoneType' object has no attribute 'parts'
```
Is this expected behaviour, and how can it be changed if not?

**Comment by peterjc** [comment]
This is a malformed feature location:

```
LOCUS       Exported                8596 bp ds-DNA     linear   SYN 18-MAY-2021
DEFINITION  3rd generation lentiviral transfer vector. pPRIME cloning plasmid 
            with a CMV promoter controlling expression of dsRed and miR30-based 
            shRNA targeting firefly luciferase.
...
     enhancer        8569..276
                     /label=CMV enhancer
                     /note="human cytomegalovirus immediate early enhancer"
...
```

The parser behaviour seems reasonable given past discussion: you get a warning (which can be caught and upgraded to an exception), and the parser does the best it can with ``None`` as the location.

Simple fix? Remove that feature, or edit it to a meaningful location.

**Comment by starling13** [comment]
I agree, the feature is incorrect. That database contains plasmid circular sequences and their fragments, formatted as linear sequences, like the given example. Thus, feature cannot cross start-end junction, formally absent in fragment sequence. I only think is this intuitive, that parsed file gives the entity record object (even producing warnings) which has "incorrect" state, throwing exception on its method call. Wouldn't it be better for "format" method to produce warning too, and ommit that feature, while forming genbank text, instead of generating exception and failing the whole process.

**Comment by peterjc** [comment]
Once upon a time the parser aborted with an exception on this kind of broken feature. The current situation is more flexible in that many use-cases don't care about the broken feature. Having a warning from the GenBank output and ignoring the feature might be acceptable... personally I am OK with the current exception. Warnings are often overlooked, so this could be a near silent failure - especially in the context of a pipeline. Still, you could open a new issue about that.

This issue is specifically about the special case with a combination of an origin wrapping feature with a problem detecting circular topology.

**Comment by mdehoon** [comment]
> Warnings are often overlooked

or may not even be generated.

**Comment by peterjc** [comment]
We need to retest this now that #3881 has been applied.

Are you familiar with installing from source @jakebeal ?

**Comment by jakebeal** [comment]
I didn't have a chance to do this last week, but aim to this week. Thank you for your patience.

**Comment by jakebeal** [comment]
I have now tested and can confirm that the patch has been successful.

With biopython-1.79, the origin-spanning feature is:
`SeqFeature(None, type='rep_origin')`

With  biopython-1.80.dev0, the origin-spanning feature is:
`SeqFeature(CompoundLocation([FeatureLocation(ExactPosition(0), ExactPosition(570), strand=-1), FeatureLocation(ExactPosition(3092), ExactPosition(3111), strand=-1)], 'join'), type='rep_origin', location_operator='join', qualifiers=...)]`

**Comment by peterjc** [comment]
That looks good - thanks for testing.
