### ISSUE TITLE
No wheels for Python 3.10 on PyPI

### ISSUE THREAD

**Issue by ShaunAl** [biopython/biopython#3824]
Hi, i am trying to install Biopython using the pip install Biopython command but I receive a n error. 

 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Asus G75VW\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Asus G75VW\\AppData\\Local\\Temp\\pip-install-8yqc8fjd\\biopython_fcf77f134fad4a56865834853fec6ce4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Asus G75VW\\AppData\\Local\\Temp\\pip-install-8yqc8fjd\\biopython_fcf77f134fad4a56865834853fec6ce4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Asus G75VW\AppData\Local\Temp\pip-record-bgk542xh\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Asus G75VW\AppData\Local\Programs\Python\Python310\Include\biopython' Check the logs for full command output.

I have installed Microsoft Visual 17.0 so i am not sure what the problem is.

Can anyone offer any help?

Best wishes.

**Comment by MarkusPiotrowski** [comment]
What exactly did you do to install Biopython via pip? Installing via pip should use a pre-compiled Windows wheel. But in your case it seems that you/your systems want to compile the source code, which should not be necessary.

**Comment by poleshe** [comment]
Hi,

You need to also install the Compiler for Microsoft Visual C++. If you follow the steps on the answer to this question @ StackOverflow, you should be able to do so.

https://stackoverflow.com/questions/49610212/pip-error-even-microsoft-visual-c-14-0-is-installed

**Comment by mdehoon** [comment]
@ShaunAl  @poleshe  : @MarkusPiotrowski  is right, a compiler should not be needed.

**Comment by eprowe** [comment]
Want to contribute that I'm seeing the same error.  Steps to replicated on a fresh Windows 10 21H2 64-bit installation.

1. Open Windows PowerShell (Admin)
2. Install Python 3.10.1 via command line using `python-3.10.1-amd64.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 Shortcuts=0`
2. Restart Windows PowerShell (Admin) in order to refresh environment variables/path
3. Execute "pip install --upgrade pip"
4. Execute "pip install --upgrade wheel"
5. Execute "pip install --upgrade setuptools"
6. Execute "pip install biopython"

Receive the following:
```
Collecting biopython
  Downloading biopython-1.79.tar.gz (16.7 MB)
  Preparing metadata (setup.py) ... done
Collecting numpy
  Downloading numpy-1.22.0-sp310-sp310-win_amd64.whl (14.7 MB)
Building wheels for collected packages: biopython
  Building wheel for biopython (setup.py) ... error
  Error: Command errored out with exit status 1:
*****{Multiple lines}*****
Complete output (731 lines)
*****{Multiple lines}*****
  Running setup.py clean for biopython
Failed to build biopython
Installing collected packages: numpy, biopython
    Running setup.py install for biopython ... error
*****{Multiple lines}*****
     copying Bio\Entrez\XSDs\IPGReportSet.xsd -> build\lib.win-amd64-3.10\Bio\Entrez\XSDs
     running build_ext
     error: Microsoft Visual C++ 14.0 or greater is required.  Get it with "Microsoft C++ Build Tools"
```
If I apply the fix outlined [HERE](https://shuchanel.com/resolve-python-pip-error-microsoft-visual-c-14-0-or-greater-is-required/), biopython installs without issue.

Attempted to install older versions (v1.73+) with the same results.

**Comment by MarkusPiotrowski** [comment]
OK, just a guess (and maybe @peterjc can comment on this): 
Usually, you do not need a compiler to install Biopython for Windows, because we provide "ready-to-use" wheels (which are already compiled). 
But: both of you are obviously using Python 3.10. 
We are currently not supporting Python 3.10. I'm not sure (but it seems so) that Python 3.10 for Windows is compiled with a newer version of the MS VC++ compiler (14.0). Obviously, pip does not download the Biopython Windows wheel, because this is compiled with an older version of the MS VC compiler, but instead downloads the uncompiled files, and then it fails because of the missing compiler.
I wonder if our installer should throw an error when trying to install in a Python 3.10 environment.

**Comment by MarkusPiotrowski** [comment]
Mmmh, according to https://matthew-brett.github.io/pydagogue/python_msvc.html Python is compiled with VC++ 15.0 already since version 3.7. So it's maybe due to our `setup.py`, which does not list Python 3.9 and 3.10?

**Comment by MarkusPiotrowski** [comment]
Okay, an updated guess: `pip` is looking in pypi for a version which is marked as usable for Python 3.10. Since there is no, it downloads the source files and tries to compile them.

I wonder if you can just use, as a workaround:
```
pip install biopython --python-version "39"
```
The existing Windows/Python 3.9 Biopython wheel should work for installing under Python 3.10 (since it is compiled with the VC compiler version).

**Comment by MarkusPiotrowski** [comment]
@peterjc BTW, `README.rst` says that we support Python 3.9, but `setup.py` does not list it.

**Comment by peterjc** [comment]
Good point, setup.py updated in 2dd97e71762af7b046d7f7f8a4f1e38db6b06c86 to include Python 3.9

And yes, our test matrix does not yet include Python 3.10, nor does the README, setup.py, etc claim we support it, and finally we don't yet attempt to build wheels for it.

But it ought to work... step one is a PR adding it to the continuous integration.

Would one of you like to try that? It should be just a tiny edit to https://github.com/biopython/biopython/blob/master/.github/workflows/ci.yml

**Comment by eprowe** [comment]
Just to confirm you suggestions.  I repeated my original procedure with 3.8.10 and it worked without issue.  Consider this a PEBKAC error assuming 3.8+ when that is not the case.  v3.8.10 is good enough for my use case.

Thanks again @MarkusPiotrowski & @oeterjc

**Comment by peterjc** [comment]
Not your fault - pip should just work with Python 3.7, 3.8, or 3.9 - but right now we don't offer a pre-compiled Biopyton for Python 3.10.

**Comment by MarkusPiotrowski** [comment]
I can just tell that I could successfully compile the latest Biopython for Python 3.10 64 bit on Windows last week. Didn't try for 32 bit (I was thinking that we do not provide wheels for 32 bit Python on Windows, but maybe I got this wrong)
Looking at @eprowe 's description and output from the installing process, it seems that he was using 64 bit Python 3.10.

**Comment by peterjc** [comment]
Yes, I could get a 64 bit Windows Python 3.10 wheel for Biopython 1.79 ``biopython-1.79-cp310-cp310-win_amd64.whl
File`` which is available for test here for a month:

https://ci.appveyor.com/project/biopython/biopython-wheels/builds/42246073/job/bivi0m15dtg1dg7j/artifacts

If someone could try that and report back, we can add that to PyPI.

It took a little tinkering, and right now 32bit is out - see https://github.com/biopython/biopython-wheels/commit/ad9910c9d15284c15c1abb199d102ac6b9f7662b and the preceding commits.

**Comment by peterjc** [comment]
I tested installing the wheel and have uploaded it to PyPI:

``biopython-1.79-cp310-cp310-win_amd64.whl``

Checksums are MD5 245b7faf6b39dc6600234a9d6d11f7de and sha256 9eadfd4300f534cd4fa39613eeee786d2c3d6b981d373c5c46616fa1a97cad10

We should have Windows Python 3.10 wheels automatically on the next release (at least for 64-bit Python, and likely 32-bit Python too as it looks like NumPy will do that later).

I think we can now close this issue. Thank you for reporting this.
