### ISSUE TITLE
internal_coords module returns different dihedral angles for the (seemingly) same protein structure

### ISSUE THREAD

**Issue by AndreeaMusat** [biopython/biopython#3875]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]

CPython
Linux-5.13.0-30-generic-x86_64-with-debian-bullseye-sid

1.79

### Expected behaviour

I am using the internal_coords module from BioPython in order to compare dihedral angles of two different conformations of the same protein. The conformations are processed by me in order to make sure that their residues are aligned and they always contain exactly the same atoms, so that in the end I expect to have the same number of dihedral angles in the two structures.

### Actual behaviour

However, despite the match in the number of chains, the number of residues, the residue names and the atom names in each residue, I obtain a different number of dihedral angles for the two conformations.

My question is, am I missing something from my comparison? Is it unreasonable to expect the same dihedral angles for these two structures? (And if yes, why?). Is this the expected behaviour of the atom_to_internal_coordinates() function?

### Steps to reproduce

You can find a reproducible code sample [here][1]. These are the two PDB files [protein1.pdb][2] and [protein2.pdb][3] used. 

  [1]: https://pastebin.com/PASnUhTa
  [2]: https://pastebin.com/FG3hLXDW
  [3]: https://pastebin.com/diFjgE3d

**Comment by peterjc** [comment]
A long time ago I wrote a torsion (psi/phi) angle example here, using the polypeptide class' ``get_phi_psi_list`` method: https://warwick.ac.uk/fac/sci/moac/people/students/peter_cock/python/ramachandran/calculate/

Does that class' ``get_tau_list`` method ("List of tau torsions angles for all 4 consecutive Calpha atoms.") do what you want?

**Comment by rob-miller** [comment]
Thanks for the detailed report with samples and code.  The issue is that the structure has some peptide bonds that are too long, and these are different between the two conformations.  I think the impact is to define additional dihedrals so the terminal atoms are specified without referencing the next residue, so in your example this generates additional keys.

If you add `verbose=True` when reading the chain you will see warnings for each break:

    ic_chain = internal_coords.IC_Chain(structure, verbose=True)

If you want to ignore this issue and just get on to the angles, raise the `IC_Chain.MaxPeptideBond` class variable above its default of 1.4, *before* reading in the chain:

    internal_coords.IC_Chain.MaxPeptideBond = 5.0
    ic_chain = internal_coords.IC_Chain(structure, verbose=True)

5.0 was the minimum value I found to get the number of dihedrals the same between the two conformations.
