### ISSUE TITLE
 I want to download version 1.65 

### ISSUE THREAD

**Issue by kdyoung100** [biopython/biopython#3903]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:  python verison 2.7  commed pip install biothon 
I want to download version 1.65

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)

**Comment by fabianegli** [comment]
Hi @kdyoung100, if you want to install older versions of a software package with pip, you can check out the software package on PyPI and  from PyPI and check out the "Release history" from where you can navigate older releases. Here's a link to the biopython package release version you were asking for: https://pypi.org/project/biopython/1.65/

**Comment by fabianegli** [comment]
Also note, that your issue text notes "pip install biothon" instead of "pip install biopython".

**Comment by peterjc** [comment]
You didn't fill in which OS you are using. Note that ``pip install biopython==1.65`` will attempt to compile the C code in Biopython. If it is Windows, then I would suggest trying the Windows installers for Biopython 1.65 which are listed on the second half of https://biopython.org/wiki/Download

(Since Biopython 1.70 we have been releasing pre-compiled wheel files on PyPI instead)

Please feel free to re-open this issue if you are still having difficulties.
