### ISSUE TITLE
seqrecord.description contains seqrecord.id

### ISSUE THREAD

**Issue by linsson** [biopython/biopython#398]
I am using

Python 2.7.8 
Biopython 1.64

I noticed that seqrecord.description contains seqrecord.id. 

Here is the fasta file (taken from http://biopython.org/DIST/docs/api/Bio.SeqRecord.SeqRecord-class.html):

$ cat test.fasta 

> YP_025292.1 toxic membrane protein
> MKQHKAMIVALIVICITAVVAALVTRKDLCEVHIRTGQTEVAVF

And here is the python code:

$ python
Python 2.7.8 (default, Oct 24 2014, 15:36:59) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from Bio import SeqIO
> > > rec = SeqIO.read("test.fasta", "fasta")
> > > rec.id
> > > 'YP_025292.1'
> > > rec.description
> > > 'YP_025292.1 toxic membrane protein'

I expected 

> > > rec.description
> > > 'toxic membrane protein'

Is this behaviour correct? I find it asymmetric compared to the Seqrecord creation process (again from http://biopython.org/DIST/docs/api/Bio.SeqRecord.SeqRecord-class.html)

Cheers

**Comment by dkoppstein** [comment]
It would be really, really nice to have round-trip functionality. I would support breaking backwards compatibility (maybe increment the version number) in order to have this. record.description, record.id, and record.name are extremely confusing. 

As an aside, it would be nice to have a common method for putting metadata into SeqRecord headers.

**Comment by peterjc** [comment]
SeqIO already has round-trip functionality (via a nasty hack in the writer code). Breaking backward compatibility on something as widely used as the FASTA parsing is not something to take lightly :(

Regarding the aside, do you specifically mean embedding values in a FASTA header (e.g. key=value pairs)? In general you might be better off using an annotation rich file format instead of FASTA.

**Comment by dkoppstein** [comment]
I see, thanks for clarifying. 

Re: embedding values, I use TSV or JSON whenever I can -- however, almost all useful programs in bioinformatics still use FASTA or FASTQ. I've seen about a dozen implementations of putting metadata into FASTA/FASTQ headers; it might be nice to have a standard implementation.
