### ISSUE TITLE
HTML tutorial has breaklines=true,breaksymbolleft=]{pycon}

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4228]
The PDF is fine, but the HTML has this at the start of some of the examples:

```
breaklines=true,breaksymbolleft=]{pycon}
```

e.g. from:

```
%cont-doctest
\begin{minted}[breaklines=true,breaksymbolleft=]{pycon}
>>> record.id
'gi|45478711|ref|NC_005816.1|'
>>> record.name
'gi|45478711|ref|NC_005816.1|'
>>> record.description
'gi|45478711|ref|NC_005816.1| Yersinia pestis biovar Microtus str. 91001 plasmid pPCP1, complete sequence'
\end{minted}
```

This might be a bug in hevea, or something we need to special case?

Workaround: Remove the options (but could downgrade the PDF output?)

Workaround: Move to Sphinx, see #907

**Comment by JoaoRodrigues** [comment]
Linking to #4227

**Comment by JoaoRodrigues** [comment]
This has been there for quite a while I suppose? I didn't update my hevea or minted installation since last time I built the release and I ran into the same issue with the output. I ran the docs building with Python 3.10 and Python 3.8, no change either.

Are those "directives" being respected at all?

**Comment by peterjc** [comment]
I'm guessing they worked on the PDF output, we can try removing them and comparing by eye?
