### ISSUE TITLE
Speed problem in developing software based on biopython

### ISSUE THREAD

**Issue by user-tq** [biopython/biopython#4241]
I have a preliminary understanding of the instructions for using biopython. 
I think this is a great project, which covers many aspects of bioinformatics. I try to use python instead of awk (to be honest, I want to solve all problems in only one language, and python has rich libraries). I need to count the distribution of the first base of each sequence. But awk is more than 20 times faster than python. I'm not proficient in python (and of course not in awk). I don't know if I have violated the taboo that affects python performance. Can you give me some suggestions?
```awk
time paste  <(zcat R1.fq.gz | awk '(NR%4==2){base=substr($0,1,1);sum[base]++;all=(NR+2)/4}END{for(i in sum) print i"\t"sum[i]"\t"sum[i]/all}')  <(zcat   R2.fq.gz |awk '(NR%4==2){base=substr($0,1,1);sum[base]++;all=(NR+2)/4}END{for(i in sum) print i"\t"sum[i]"\t"sum[i]/all}')
```
```python
import gzip
from Bio import SeqIO
import pandas as pd
import argparse

# pip install biopython  pandas

parser = argparse.ArgumentParser(description='统计umi5、6位置脚本')
parser.add_argument("-r1","--r1_fq_gz", required=True,help='r1 fq.gz')
parser.add_argument("-r2","--r2_fq_gz", required=True,help='r2 fq.gz')
parser.add_argument("-o","--out", required=True,help='统计文件tsv')
args = parser.parse_args()


def fq_to_pd(fqgz,lenth):
    file_list=[]
    with gzip.open(fqgz, "rt") as handle:
        for record in SeqIO.parse(handle, "fastq"):
            file_list.append([record.id.split('/')[0],str(record.seq)[0:lenth]])
    
    file_df=pd.DataFrame(file_list,columns = ['id', 'umi'])
    return file_df

df_1=fq_to_pd(args.r1_fq_gz,1)
df_2=fq_to_pd(args.r2_fq_gz,1)

df=pd.merge(df_1,df_2,on='id',how='outer',suffixes=('_r1','_r2'))


df['pos1_r1']=df['umi_r1']
df['pos1_r2']=df['umi_r2']

r1_sum=pd.merge(df['pos1_r1'].value_counts(dropna=False, normalize=True).reset_index(),df['pos1_r1'].value_counts(dropna=False).reset_index(),suffixes=('占比','总数'),on='index',how='outer')
r2_sum=pd.merge(df['pos1_r2'].value_counts(dropna=False, normalize=True).reset_index(),df['pos1_r2'].value_counts(dropna=False).reset_index(),suffixes=('占比','总数'),on='index',how='outer')

all_sum=pd.merge(r1_sum,r2_sum,on='index',how='outer')

all_sum=all_sum.fillna(0)
all_sum['pos1_r1占比']=all_sum['pos1_r1占比'].round(decimals=5) #.apply(lambda x : '%.5f' % x)  
all_sum['pos1_r2占比']=all_sum['pos1_r2占比'].round(decimals=5)#  .apply(lambda x : '%.5f' % x) 


print(all_sum)

#all_sum.to_csv(args.out,sep='\t')
```

![image](https://user-images.githubusercontent.com/72878144/220025085-87fd1d23-569e-4a51-b239-2edcea6e4146.png)

**Comment by Lucioric2000** [comment]
Hi, have you tried collections.Counter over the Seq underlying string object?.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: lunes, 20 de febrero de 2023 12:15 a. m.
Para: ***@***.***>
CC: ***@***.***>
Asunto: [biopython/biopython] Speed problem in developing software based on biopython (Issue #4241)


I have a preliminary understanding of the instructions for using biopython.
I think this is a great project, which covers many aspects of bioinformatics. I try to use python instead of awk (to be honest, I want to solve all problems in only one language, and python has rich libraries). I need to count the distribution of the first base of each sequence. But awk is more than 20 times faster than python. I'm not proficient in python (and of course not in awk). I don't know if I have violated the taboo that affects python performance. Can you give me some suggestions?

time paste  <(zcat R1.fq.gz | awk '(NR%4==2){base=substr($0,1,1);sum[base]++;all=(NR+2)/4}END{for(i in sum) print i"\t"sum[i]"\t"sum[i]/all}')  <(zcat   R2.fq.gz |awk '(NR%4==2){base=substr($0,1,1);sum[base]++;all=(NR+2)/4}END{for(i in sum) print i"\t"sum[i]"\t"sum[i]/all}')

import gzip



from Bio import SeqIO



import pandas as pd



import argparse







# pip install biopython  pandas







parser = argparse.ArgumentParser(description='统计umi5、6位置脚本')



parser.add_argument("-r1","--r1_fq_gz", required=True,help='r1 fq.gz')



parser.add_argument("-r2","--r2_fq_gz", required=True,help='r2 fq.gz')



parser.add_argument("-o","--out", required=True,help='统计文件tsv')



args = parser.parse_args()











def fq_to_pd(fqgz,lenth):



    file_list=[]



    with gzip.open(fqgz, "rt") as handle:



        for record in SeqIO.parse(handle, "fastq"):



            file_list.append([record.id.split('/')[0],str(record.seq)[0:lenth]])







    file_df=pd.DataFrame(file_list,columns = ['id', 'umi'])



    return file_df







df_1=fq_to_pd(args.r1_fq_gz,1)



df_2=fq_to_pd(args.r2_fq_gz,1)







df=pd.merge(df_1,df_2,on='id',how='outer',suffixes=('_r1','_r2'))











df['pos1_r1']=df['umi_r1']



df['pos1_r2']=df['umi_r2']







r1_sum=pd.merge(df['pos1_r1'].value_counts(dropna=False, normalize=True).reset_index(),df['pos1_r1'].value_counts(dropna=False).reset_index(),suffixes=('占比','总数'),on='index',how='outer')



r2_sum=pd.merge(df['pos1_r2'].value_counts(dropna=False, normalize=True).reset_index(),df['pos1_r2'].value_counts(dropna=False).reset_index(),suffixes=('占比','总数'),on='index',how='outer')







all_sum=pd.merge(r1_sum,r2_sum,on='index',how='outer')







all_sum=all_sum.fillna(0)



all_sum['pos1_r1占比']=all_sum['pos1_r1占比'].round(decimals=5) #.apply(lambda x : '%.5f' % x)



all_sum['pos1_r2占比']=all_sum['pos1_r2占比'].round(decimals=5)#  .apply(lambda x : '%.5f' % x)











print(all_sum)







#all_sum.to_csv(args.out,sep='\t')

[image]<https://bra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F72878144%2F220025085-87fd1d23-569e-4a51-b239-2edcea6e4146.png&data=05%7C01%7C%7C4aaec1e8b4c44e2be48108db1309ed3e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638124705596260990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4JofQF9%2FMVipAg9aZWzUhqX3UsR5QlM%2F7v2wjEGgtV0%3D&reserved=0>

―

**Comment by peterjc** [comment]
Don't use ``Bio.SeqIO.parse(...)`` with the heavy ``SeqRecord`` objects. Use the low-level string based FASTQ parser instead. See e.g. https://www.open-bio.org/2009/09/25/biopython-fast-fastq/

And I'd also try something simpler than pandas for that actual tallying of the bases, probably the built-in Python dictionary.

**Comment by peterjc** [comment]
Closing due to lack of any followup discussion.
