### ISSUE TITLE
 Concerns about BiopythonDeprecationWarning in Bio.pairwise2

### ISSUE THREAD

**Issue by mrdanieleze** [biopython/biopython#4614]
Hello Biopython community,

I hope this message finds you well. I'm writing to express my concerns regarding the BiopythonDeprecationWarning that appears in the Bio.pairwise2 module. It seems that even after updating Biopython from version 1.81 to 1.83, the warning persists. I would appreciate any guidance or clarification on whether this warning is intentional or if there's a recommended alternative.

I have successfully implemented a solution using the Bio.Align.PairwiseAligner module, and I'm curious if there are plans to fully deprecate Bio.pairwise2 or if this is an oversight in the documentation.

Thank you for your time and assistance.

Best regards, Daniel Eze
![Screenshot 2024-01-31 203817](https://github.com/biopython/biopython/assets/158342252/29e5140e-e0e8-41f0-afb5-8ce1d0b8ede3)

**Comment by mdehoon** [comment]
The warning is intentional. As written in the warning message, we recommend using Bio.Align.PairwiseAligner as an alternative. The main purpose of the warning is to find out if there are any use cases of Bio.pairwise2 that cannot be covered by Bio.Align.PairwiseAligner.

**Comment by mrdanieleze** [comment]
> The warning is intentional. As written in the warning message, we recommend using Bio.Align.PairwiseAligner as an alternative. The main purpose of the warning is to find out if there are any use cases of Bio.pairwise2 that cannot be covered by Bio.Align.PairwiseAligner.

Hi mdehoon,Thank you for your prompt response and clarification on the deprecation of Bio.pairwise2. I appreciate the efforts in developing and recommending Bio.Align.PairwiseAligner as an alternative. However, after attempting to migrate, I encountered specific challenges that I'd like to discuss:

Normalization of Scores: My application requires the alignment scores to be normalized within a specific range (0 to 10). Unfortunately, achieving this with Bio.Align.PairwiseAligner has proven challenging, impacting the interpretability of the results.

Complexity and Inconsistency: The complexity of Bio.Align.PairwiseAligner has led to inconsistent results, making it difficult to extract meaningful information from the alignments.

I understand the importance of evolving and adopting new tools, but for my current use case, the existing code with Bio.pairwise2 meets my needs more effectively. I'm open to suggestions or guidance on overcoming the challenges I've encountered.

**Comment by peterjc** [comment]
I'll leave most of this to Michiel, but a minor clarification if you would: "*The complexity of Bio.Align.PairwiseAligner has led to inconsistent results*", is that inconsistencies compared to what Bio.pairwise2 did, or inconsistencies within Bio.Align.PairwiseAligner? Either way, an example would be helpful.

And as to the timing, see https://biopython.org/wiki/Deprecation_policy - the warning has been in place for Biopython from version 1.80 (November 2022) to 1.83 (current release, Jan 2024). This therefore exceeds the minimums of a year and two releases promised, and thus potentially we could remove Bio.pairwise2 in the next release. This didn't happen earlier because we've had multiple enquires, although I believe they were all addressed. Hopefully yours can be too.

**Comment by mrdanieleze** [comment]
Thank you all for your comments and contributions. I'm pleased to announce that I've successfully resolved the BioPythonDeprecatioWarning in Bio.pairwise2, by updating the Genomic Sequence Comparison Code (GSCC) to use the Bio.Align. Your valuable input was instrumental in finding this solution. If you have further questions or feedback, feel free to reach out. Cheers!
