### ISSUE TITLE
Significant RMSD Difference between BioPython and PyMol

### ISSUE THREAD

**Issue by universvm** [biopython/biopython#4632]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0]
CPython
Linux-5.14.0-1058-oem-x86_64-with-glibc2.17
1.83

### Expected behaviour

I expect the RMSD of PyMol CEaling and Biopython to be the same

### Actual behaviour

There are differences between the RMSD of PyMol CEaling and Biopython

### Steps to reproduce

I created this minimal version to calculate rmsd between two structures:

```python
import pymol
from pymol import cmd
from Bio.PDB import PDBParser
from Bio.PDB.cealign import CEAligner
import ampal
import tempfile

def calculate_rmsd_cealigner(pdb_file_1, pdb_file_2):
    # Initialize the PDB parser
    parser = PDBParser()

    # Parse the two structures
    structure1 = parser.get_structure('structure1', pdb_file_1)
    structure2 = parser.get_structure('structure2', pdb_file_2)

    # Initialize the CEAligner
    ce_aligner = CEAligner()

    # Perform the alignment
    ce_aligner.set_reference(structure1)
    ce_aligner.align(structure2)

    # Get the RMSD from the alignment
    rmsd = ce_aligner.rms

    return rmsd

def calculate_rmsd_pymol(reference_pdb_path, fragment_pdb_path, normalize=True) -> float:
    pymol.pymol_argv = ["pymol", "-qc"]  # Quiet mode, without GUI
    pymol.finish_launching()
    
    cmd.delete("all")  # Clear any loaded objects
    cmd.load(reference_pdb_path, object="reference")
    cmd.load(fragment_pdb_path, object="fragment")

    # Perform the structural alignment using the align command
    alignment_result = cmd.cealign("reference and name CA", "fragment and name CA")
    rmsd = alignment_result['RMSD']  # Extract RMSD from the result
    return rmsd
```

Using the same input:

```
calculate_rmsd_pymol("../data/pdbs/1A8P.pdb1", "../data/pdbs/1A62.pdb1" )
>>> 7.360173298876859
calculate_rmsd_cealigner("../data/pdbs/1A8P.pdb1", "../data/pdbs/1A62.pdb1")
>>> 6.260138014728223
```

@JoaoRodrigues suggested that I open an issue here. I'm attaching the files in case they can be helpful. Let me know if I can help!
[pdb_structures.zip](https://github.com/biopython/biopython/files/14318477/pdb_structures.zip)

**Comment by JoaoRodrigues** [comment]
Thanks for posting the issue here @universvm.

There is a difference in how the alignment is processed between Pymol and Biopython. For some context, the cealign algorithm works in two steps: first it finds candidate aligned fragments, and then it uses superimposition to pick the best candidate (lowest RMSD). In Pymol, the superimposition is done using Kabsch's algorithm (SVD) whereas in Biopython we use a faster quaternion-based method (qcprot). So, while the candidate fragments are guaranteed to be exactly the same between Pymol and Biopython, the resulting alignment can differ _slightly_.

In your specific case, there is very little structural homology that I can see between those two structures, thus the high RMSD values. My guess is in this case, since the homology is so poor, the two superimposers find slightly different solutions and you see a larger discrepancy between the two programs. 

I am inclined to close this as not an issue, but I'll wait for your comment.

**Comment by universvm** [comment]
Hi @JoaoRodrigues ,

Thanks for the explanation, I see your point. I'd say let's close the issue for the moment. I'm currently doing a few experiments with this. I'll reopen the issue if I notice major differences in RMSD 

Thanks again!
