### ISSUE TITLE
genbank writer doesnt write qualifier value if it is zero

### ISSUE THREAD

**Issue by cfblaeb** [biopython/biopython#470]
I have a seqrecord.
I add a feature with a qualifier dictionary, e.g. qualifiers={"something": 0, "other": 5}
It saved the feature correctly, with the correct values in the qualifiers dictionary.
When i write the seqrecord to file using the following code:
SeqIO.write(my_seqrec, open("test.gb", "w"), "genbank")

Then it writes the "other" value correctly, but leaves "something" blank. No zero.
It should write the zero.

**Comment by peterjc** [comment]
Ah. This is mistakenly trying your "something" qualifier as a value-less entry like the ``/pseudo`` qualifiers used in GenBank, but I can see how to fix it...

**Comment by cfblaeb** [comment]
thank you very much

**Comment by peterjc** [comment]
Thank you for reporting this bug. It should now be fixed on the master branch and will be part of our next release.

I assume you would like to fix your local copy of Biopython? Are you comfortable installing Biopython from source from git? If so that would be the simplest approach.

The alternative (assuming you already have Biopython 1.65 which is our latest release) may be to manually update your already installed ``.../Bio/SeqIO/InsdcIO.py`` file to match https://raw.githubusercontent.com/biopython/biopython/cd86bb26a3a6d7568fa7059d028d0a4e1fc3085a/Bio/SeqIO/InsdcIO.py (i.e. with the change in https://github.com/biopython/biopython/commit/cd86bb26a3a6d7568fa7059d028d0a4e1fc3085a applied).

If neither of those make sense, or you'd like more precise guidance please let me know (as a reply here is fine). If so, it would help to know which OS you are using (Windows? Linux?), and which version of Python.

**Comment by cfblaeb** [comment]
I'll just install from git. Thank you for your quick response and fix.

**Comment by peterjc** [comment]
Great - please report back if I've overlooked something else while tweaking this.
