### ISSUE TITLE
GC content for RNA sequences

### ISSUE THREAD

**Issue by Lucandia** [biopython/biopython#4722]
### Setup

I am reporting a problem with:
-  Biopython version: 1.81
- Python version: 3.9.0
- System: macOS Sonoma

### Expected behaviour

```
from Bio.SeqUtils import gc_fraction
gr_fraction("GGAUCUUCGGAUCU") 
# expected result: 0.5
```

### Actual behaviour

```
from Bio.SeqUtils import gc_fraction
gr_fraction("GGAUCUUCGGAUCU") 
# result: 0.7777777777777779
```

### What to fix
Please add U to the non-ambiguous nucleotides to support RNA sequences (currently, the non-ambiguous nucleotides are ATCGSW). The previous GC content function (now deprecated) was supporting RNA sequences too

**Comment by peterjc** [comment]
The old function didn't explicitly handle U either:

```python
def GC(seq):
    """Calculate G+C content (DEPRECATED).
    Use Bio.SeqUtils.gc_fraction instead.
    """
    warnings.warn(
        "GC is deprecated; please use gc_fraction instead.",
        BiopythonDeprecationWarning,
    )

    gc = sum(seq.count(x) for x in ["G", "C", "g", "c", "S", "s"])
    try:
        return gc * 100.0 / len(seq)
    except ZeroDivisionError:
        return 0.0
```

(See 960a5e2c9e98ce3b1b207cffcd818c3ffcf60bde which removed it)

To mimic the old behaviour, use the ignore mode rather than the default remove mode:

```pycon
>>> from Bio.SeqUtils import gc_fraction
>>> gc_fraction("GGAUCUUCGGAUCU", "ignore") 
0.5
```

That said, explicitly handling `U` for RNA support makes sense. I think it would be a one line change to add `U` to the dictionary here:

https://github.com/biopython/biopython/blob/biopython-183/Bio/SeqUtils/__init__.py#L32

This would also need a new test case (e.g. your example). Would you like to make a pull request?

**Comment by Lucandia** [comment]
Sure, I'm on it!
