### ISSUE TITLE
BiopythonDeprecationWarning in Bio.pairwise2

### ISSUE THREAD

**Issue by eyal-scala** [biopython/biopython#4733]
Hello, 
I am trying to replicate the behavior of Bio.pairwise2 using PairwiseAligner. I appear to be getting many more alignments 
when using PairwiseAligner. Why is this occuring? 
Is there a way to force PairwiseAligner to align exactly like Bio.pairwise2?
Both are used with global allignment, and default settings which appear to be the same.

attached is a txt file with the alignment comparison.
[alignment comparison.txt](https://github.com/biopython/biopython/files/15386063/alignment.comparison.txt)

Thanks!

**Comment by MarkusPiotrowski** [comment]
@eyal-scala While I can not help you to set the `PairwiseAligner` to return the same number of alignments as `pairwise2`, I can explain the difference for the examples that you showed.

The backtrace method of `pairwise2`  (`_recover_alignments()`) does not return alignments which are just differing by the position of two consecutive alternating gaps in both sequences. To be more clear, I cite the comment from the method here:
```
# Although we allow a gap in seqB to be followed by a gap in seqA,
# we don't want to allow it the other way round, since this would
# give redundant alignments of type: A-  vs.  -A
#                                    -B       B-
# Thus we need to keep track if a gap in seqA was opened (col_gap)
# and stop the backtrace (dead_end) if a gap in seqB follows.
```

**Comment by mdehoon** [comment]
To follow up on @MarkusPiotrowski  's comment, the `PairwiseAligner` does not apply such filtering because it is very difficult to design a general filtering rule that keeps everybody happy. For example, someone may be aligning an RNA fragment to genomic DNA and may want to keep gaps in the RNA only. Someone else may want to keep gaps in the DNA only. And for other applications, people will want to keep all alignments. You can of course filter the alignments generated by the `PairwiseAligner` yourself and skip the ones that are redundant or not relevant for your particular application.

For both aligners, if you get many alignments, they are likely to be poor alignments and you may want to play with the scoring parameters.

**Comment by mdehoon** [comment]
Btw an easy way to identify alignments that are identical except for their gap positions is to look at the `aligned` property of each alignment:
```python
>>> from Bio.Align import PairwiseAligner
>>> aligner = PairwiseAligner()
>>> alignments = aligner.align("ACGT", "ACGA")
>>> len(alignments)
3
>>> for alignment in alignments:
...     print(alignment)
...     print(alignment.aligned)
... 
target            0 ACGT- 4
                  0 |||-- 5
query             0 ACG-A 4

[[[0 3]]

 [[0 3]]]
target            0 ACG-T 4
                  0 |||-- 5
query             0 ACGA- 4

[[[0 3]]

 [[0 3]]]
target            0 ACGT 4
                  0 |||. 4
query             0 ACGA 4

[[[0 4]]

 [[0 4]]]
>>>
```
Two alignments are redundant (in the `Bio.pairwise2` definition) if their `aligned` property is the same. Then, for each value of `aligned`, you pick just one of the alignments.

**Comment by eyal-scala** [comment]
Thank you very much for your responses!

**Comment by mdehoon** [comment]
@eyal-scala  Can we close this issue?
