### ISSUE TITLE
Google search reports the www.biopython.org site as hacked

### ISSUE THREAD

**Issue by martenson** [biopython/biopython#477]
![screenshot 2015-02-21 17 46 04](https://cloud.githubusercontent.com/assets/1814954/6316358/b99bbc70-b9f1-11e4-8158-d7c927449d88.png)

The link leads here: https://support.google.com/websearch/answer/190597?p=ws_hacked&rd=1

**Comment by peterjc** [comment]
CC @tiagoantao who reported this last week (although for a sub page of the wiki), I currently see at least two sub-pages flagged:

https://www.google.co.uk/search?client=safari&rls=en&q=google&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=l4rpVNyjNtTH8gfarYHQCQ&gws_rd=cr#rls=en&q=+site:biopython.org+biopython+faq

Finding out more from Google seems to ideally require uploading a file as http://www.biopython.org/googleXXX.html which may be tricky given how the wiki owns that part of the namespace...

**Comment by saketkc** [comment]
It should be possible to avoid that using `mod_rewrite`, perhaps?
This might be helpful: http://wiki.dreamhost.com/Mod_rewrite

**Comment by peterjc** [comment]
After adding an alias in the Apache configuration file I can create the Google HTML verification file at the desired URL, the trouble is Google says the contents do not match what they gave me to download... I've emailed our volunteer SysAdmin team on root-l for help.

**Comment by peterjc** [comment]
It turns out the Google "HTML" verification file is really one line of plain text - the trick is to actually download it via your browser where you are already logged into Google. Using ``wget`` or ``curl`` gives you a rich HTML log-in page instead. Having verified ownership and enabled Google’s Webmaster Tools, there are no reported security problems (!).

However the bad news is yes, we have found a problem - apparently the server is being used for SEO trickery to promote links to online pharmacists :(

**Comment by martenson** [comment]
Wow, so Google got it right. I am impressed.

**Comment by peterjc** [comment]
This is still being worked on.

As a potential medium term option, I am also exploring a potential migration from MediaWiki to GitHub Pages, see:
http://lists.open-bio.org/pipermail/biopython-dev/2015-March/020825.html
https://github.com/peterjc/mediawiki_to_git_md

**Comment by carlosmr12** [comment]
This issue seems to be fixed. The message is not being displayed here for me.

**Comment by martenson** [comment]
@carlosmr12 seems correct. I do not encounter this issue anymore.
