### ISSUE TITLE
Function detail require for API Documentation

### ISSUE THREAD

**Issue by DoubleBobCat** [biopython/biopython#4794]
### Expected and Actual

The standard API documentation on https://biopython.org/docs/latest/api suggests showing the input and return, even if it is not on the function's detail page.

For example, in https://biopython.org/docs/latest/api/Bio.Blast.html, the `NcbiblastpCommandline` function not shown as `NcbiblastpCommandline`, but displayed like the detail page:

```python
class Bio.Blast.Applications.NcbiblastpCommandline(cmd='blastp', **kwargs)
```

An API document example that can be used for reference is https://docs.opencv.org/4.8.0/d0/de1/group__core.html

In this way, coders using can be easier to find the function they want, and faster to code.

**Comment by peterjc** [comment]
I'm not clear what you are asking for. An example from another Python project might help, ideally one also using Sphinx for the API documentation.

Also, ``NcbiblastpCommandline`` is deprecated, so a different class/function might be more helpful. Looking at this now, I see 50bb85b0298a978f0adb34a80b67144917d01b37 was too narrow and there are likely other application wrappers which still only say "obsolete" rather than "deprecated" in their docstrings. e.g. ``Bio/Blast/Applications.py`` and ``Bio/Align/Applications/__init__.py`` were also missed during #4520.

**Comment by peterjc** [comment]
Closing for lack of followup information.
