### ISSUE TITLE
Biopython record.dbxrefs chews last two characters of long Uniprot IDs

### ISSUE THREAD

**Issue by Rohit-Satyam** [biopython/biopython#4859]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
```
3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 18:49:41) 
[GCC 9.4.0]
CPython
Linux-5.4.0-196-generic-x86_64-with-debian-bullseye-sid
1.79
```

When I parse the following PDB file from the Alphafold database, I see the `record.dbxrefs` strips the last two characters of the UniProt ID if they are too long:

```python
for record in SeqIO.parse("AF-A0A143ZUM0-F1-model_v4"+".pdb", "pdb-seqres"):
    pdb_id = record.id.strip().split(':')[0]
    chain  = record.annotations["chain"]
    _, UNP_id = record.dbxrefs[0].strip().split(':')
    print(record.dbxrefs[0])
    print(pdb_id,chain,UNP_id)
```
```
UNP:A0A143ZU
XXXX A A0A143ZU
```
But works for files like `AF-Q7KQK0-F1-model_v4`

```python
for record in SeqIO.parse("AF-Q7KQK0-F1-model_v4"+".pdb", "pdb-seqres"):
    pdb_id = record.id.strip().split(':')[0]
    chain  = record.annotations["chain"]
    _, UNP_id = record.dbxrefs[0].strip().split(':')
    print(record.dbxrefs[0])
    print(pdb_id,chain,UNP_id)
```
```
UNP:Q7KQK0
XXXX A Q7KQK0
```

Can this be fixed or avoided?

**Comment by thrs79136** [comment]
Upon first inspection it seems like the file `AF-A0A143ZUM0-F1-model_v4.pdb` does not follow the standard defined by
http://www.wwpdb.org/documentation/file-format-content/format33/sect3.html#DBREF
which requires the Sequence database accession code to be a string with 8 characters and it should use DBREF1 or DBREF2 instead of the DBREF column.

As a workaround you could use 
```
_, UNP_id = record.dbxrefs[1].strip().split('UNP:0 ')
```
instead.

**Comment by peterjc** [comment]
I agree with @thrs79136

Quoting from http://www.wwpdb.org/documentation/file-format-content/format33/sect3.html#DBREF

```
27 - 32       LString       database           Sequence database name.
34 - 41       LString       dbAccession        Sequence database accession code.
43 - 54       LString       dbIdCode           Sequence  database identification code.
```

and their example:

```
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
DBREF  2JHQ A    1   226  UNP    Q9KPK8   UNG_VIBCH        1    226 
```

Assuming the problem file ``AF-A0A143ZUM0-F1-model_v4.pdb`` matches https://alphafold.ebi.ac.uk/files/AF-A0A143ZUM0-F1-model_v4.pdb then yes, it is invalid:

```
DBREF  XXXX A    1  1233  UNP    A0A143ZUM0 A0A143ZUM0_PLAF7     1   1233
```

The database name is fine:

```
$ grep ^DBREF AF-A0A143ZUM0-F1-model_v4.pdb | cut -c 27-32
UNP   
```

The accession is too long for the dbAccession field, with extra letters ``M0`` at columns 42-43 

```
$ grep ^DBREF AF-A0A143ZUM0-F1-model_v4.pdb | cut -c 34-41
A0A143ZU
```

This likely pushed the dbIdCode field out of position: 

```
$ grep ^DBREF AF-A0A143ZUM0-F1-model_v4.pdb | cut -c 43-54
0 A0A143ZUM0
```

We could add a warning if there isn't a space at column 42, but otherwise this seems to be working as expected.

I think the answer to your question "*Can this be fixed or avoided?*" is yes: AlphaFold need to use the DBREF1/DBREF2 lines instead.

Again quoting the PDB docs:

> DBREF1/DBREF2 replaces DBREF when the accession codes or sequence numbering does not fit the DBREF format.

You might also try the mmCIF file?
