### ISSUE TITLE
Support Python 3.13

### ISSUE THREAD

**Issue by corneliusroemer** [biopython/biopython#4883]
Currently it looks like Biopython doesn't yet support Python 3.13 which has been out for ~1 month. Would be great to add it in the next release!

While I couldn't find specific mentions of Biopython being pinned to <3.13, the fact that conda-forge does not have any builds for 3.13 means it's effectively out of bounds for us.

**Comment by michaelfm1211** [comment]
Based on my experimentation, Biopython works perfectly fine (successfully builds and passes tests) on Python 3.13 if experimental free-threading is turned off. If it is turned on, Biopython successfully builds and passes tests, but modules with C extensions raise a warning about not specifying whether or not they are safe without the GIL. Also, features that require SciPy to be installed are unavailable because SciPy doesn't support free-threading mode (https://github.com/scipy/scipy/issues/21675).

Based on https://github.com/conda-forge/biopython-feedstock/pull/49, it looks like conda-forge is waiting for the 1.85 release of Biopython since the current 1.84 doesn't build on Python 3.13

**Comment by peterjc** [comment]
As discussed on the conda-forge issue, all that blocks Python 3.13 with the current release of Biopython 1.64 is a C compilation issue which is fixed on the master branch - https://patch-diff.githubusercontent.com/raw/biopython/biopython/pull/4706.patch - that is looking wise in the very short term.

Or waiting for Biopython 1.65, which I would have liked to have out already. I had time in September https://lists.open-bio.org/pipermail/biopython/2024-September/017067.html but don't in the short term - maybe next week?

**Comment by mdehoon** [comment]
I am seeing a bunch of errors with Python 3.13 with the current master branch. I am not sure if these are bugs in Biopython, or issues with Python 3.13.0.

**Comment by peterjc** [comment]
@mdehoon can you elaborate? Things seemed fine in my testing, and on GitHub Actions -  see https://github.com/biopython/biopython/pull/4892 for including Python 3.13 in our CI testing.

**Comment by peterjc** [comment]
As far as I know, everything is fine with Python 3.13.

There is a new issue with NumPy 2.2 (recently released).

I hope to do the Biopython 1.85 release next week (once work has shut for the Christmas break).
