### ISSUE TITLE
Pickling and unpickling an Entrez.read() results in error

### ISSUE THREAD

**Issue by mathiasbockwoldt** [biopython/biopython#514]
I'm trying to get taxonomy information about various species. In order to not bother NCBI too much, I try to cache the results using pickle. Pickling works fine, however, interpreting the unpickled data results in an exception:

```
Traceback (most recent call last):
  File "./biopythonGetTaxonomyByName.py", line 50, in <module>
    data = pickle.load(open('biopython_cache/taxid_' + str(taxid) + '.p', 'rb'))
  File "/usr/local/lib/python3.4/dist-packages/Bio/Entrez/Parser.py", line 115, in __setitem__
    if key in self.listkeys:
AttributeError: 'StructureElement' object has no attribute 'listkeys'
```

An example of reproducing the error follows:

```python
from Bio import Entrez
import pickle
Entrez.email = 'A.N.Other@example.com' # enter your email address here
taxid = '9606' # Homo sapiens
search = Entrez.efetch(id = taxid, db = "taxonomy", retmode = "xml")
data = Entrez.read(search)
pickle.dump(data, open('taxid_' + str(taxid) + '.p', 'wb'))
data2 = pickle.load(open('taxid_' + str(taxid) + '.p', 'rb'))
```

The last line will result in the abovementioned exception.

**Comment by peterjc** [comment]
Personally I would always cache the raw XML as a file instead. This ought to be robust to things like switching Python versions etc, and is useful for manual inspection of the incoming data (e.g. with grep). However, for short term caching pickle ought to be fine...

Trying your example, it works for me on Mac OS X with Python 2.6 and 2.7, but fails as described with Python 3.3 and 3.4; CC @mdehoon 

(Jython 2.7 fails due to its incomplete XML parsing support; PyPy seems to fail in a different way with ``EOFError`` which is odd).

**Comment by mathiasbockwoldt** [comment]
Yes, saving the XML file is the best idea, you are right. I will do that, thank you!

For the pickling problem: I'm sorry, I forgot to tell you the computer details. I'm using Python 3.4 on Linux Mint 17.

**Comment by mdehoon** [comment]
Saving Python objects using pickle is actually quite tricky. See the Python documentation for an example. As far as I can tell, this is not a bug in Biopython.

**Comment by mathiasbockwoldt** [comment]
OK. From my point of view, it is fine as it is now. Saving the XML file is probably better anyway.
Thank you!
