### ISSUE TITLE
HmmerIO text parser breaks on sequence hits without individual domain hits

### ISSUE THREAD

**Issue by tryptochan** [biopython/biopython#525]
I am using the latest Hmmer 3.1b2 with a custom library. There is no description for proteins in the library.

The **hmmer3-text** parser fails on hits with "[No individual domains that satisfy reporting thresholds (although complete target did)]", rasing the ValueError "Expected Hit with query description `qdesc`, found `hqdesc` instead".

It seems only for these hits, like 2eq4_A in the example file, the `hqdesc` is assigned to the query description, while for other hits, it is the placeholder "<unknown description>".

The codes in the `_create_hits` function seem to assign the description. But I have no idea of why this is done like that.
```
if not hit:
   hit.query_description = qdesc
```

[A example file] (https://gist.github.com/tryptochan/4e987981b7c4dd11ac6e)

**Comment by tryptochan** [comment]
I was printing out `qdesc` and `hqdesc` before the assertion statement.

I am a little bit confused now because the descriptions are actually both "unknown description" for other good hits. But for 2eq4, it is "unknown description" versus "Protein-arginine kinase ...". I thought the query description should be parsed and populated to hits and agreement is checked.

**Comment by bow** [comment]
Hi @tryptochan ,

Apologies for the delay, but I finally have time to fully work on this now. The boolean check for `hit` is done because the `query_description` property can be set in two ways: from the hit object itself or from all the HSPs object contained within.

The default is to use the HSPs contained within, since all HSPs contain description about their hits and queries. When this is the case and `Hit` has at least one `HSP` in it, `hit.query_description` actually fetches the HSP's `query_description`.

It is possible, for example in your case, to have hits without HSPs. And in this case, the parser sets the `query_description` manually.

Now, the error occurs because the object that contains the `Hit`s, the `QueryResult` object, expects all of its hits to have the same `query_description` value. The part that raises the exception is a validation step that was added to ensure that querying one hit's `query_description` would be the same as querying any other. 

The bug itself, though, is apparently because the parser does not set the correct query and hit descriptions at the underlying HSP (well, the fragments that the HSP contain) objects.

I've made a fix and will push a pull request soon :).

**Comment by tryptochan** [comment]
Thanks!

**Comment by jeanrjc** [comment]
Hi,

I don't know whether I'd rather open a new issue or not.

Anyway I have the same error `ValueError: Expected Hit with query description '<unknown description>', found 'resistance-nodulation-cell division (RND) antibiotic efflux pump [ARO:0010004]' instead` with Biopython 1.65.

I only have this error when the `--cut_ga` option is set when calling hmmsearch. It does not break on all sequences though nor with all profiles. Maybe you're aware of this ? I'll try to find a downloadable sequence that reproduce the error and I'll create a new issue with all the reproducible material.

Thanks

**Comment by peterjc** [comment]
@jeanrjc The changes above were made in July 2015, so would be in Biopython 1.66 (released October 2015). Could you upgrade and retest, and if the problem is still there please file a new issue? Thanks!

**Comment by jeanrjc** [comment]
@peterjc Thank you very much ! It works !
I have tried to upgrade to 1.66 without much insistence after `pip` failed because I wasn't sure it was released. So thanks for confirming that I had to upgrade (which I did but not with pip), now it works.
