### ISSUE TITLE
Embl write bug

### ISSUE THREAD

**Issue by EBosi** [biopython/biopython#561]
I found this issue when writing an embl file with Biopython.
The embl file generated should contain a line with "XX" before the line with the DNA sequence (the line starting with "SQ"), while the file generated using the Bio.SeqIO.write does not. This can lead to errors, i.e. the Colombo software that uses BioPerl gives an error when parsing an embl file generated with BioPython.

Hope to be clear, this was my first issue ever on github.

**Comment by peterjc** [comment]
Yes, you're right - well spotted. I think most EMBL parsers ignore the ``XX`` lines which would explain why no one had noticed this till now.

**Comment by peterjc** [comment]
I think I've fixed this, and the change will be in the next release of Biopython.

If you're comfortable installing Biopython from source, then getting the latest version for GitHub would be the cleanest way to try this. Otherwise, it should be quite simple to add this one line to your locally installed copy of ``Bio/SeqIO/InsdcIO.py``. Please ask if you need guidance.

Thanks for reporting this :)

**Comment by EBosi** [comment]
Dear Peter,
Thanks for the quick fix!
Bests,
Emanuele
Il 12/giu/2015 18:24 "Peter Cock" <notifications@github.com> ha scritto:
