### ISSUE TITLE
Is there any easy way to retrieve the transcript for a gene by Biopython?

### ISSUE THREAD

**Issue by ajing** [biopython/biopython#568]
I saw UniGene. Currently, I have gene symbol from UniProt. I didn't see the corresponding field for gene symbol in UniGene. Is that possible to do it? Retrieve transcript by a gene symbol?

**Comment by fomightez** [comment]
I didn't find it built-in to Biopython, but I admit I didn't exhaustively search as it seems overly specialized given varying degree of experimental support vs. deduced, different depositors' behavior and different extent database linking, etc.. So to do that I used Biopython as a module to build my own scripts on top of, but my input is based on NCBI fasta sequences of the protein or proteins of interest. You'd have to switch over to that if you are interested in using my code. See [here](https://github.com/fomightez/sequencework/tree/master/RetrieveSeq).  The second one, GetmRNAorCDSforProtein.py, is more tenacious because it doesn't rely necessarily on a separately linked `mRNA` entry existing for the protein. It will use a series of increasingly demanding measures to try and obtain the messenger RNA or coding sequence (CDS).

FYI,  it won't work as written once the GI sequence identifiers get phased out as described in section 1.4.1 of the [June 15 2015 Distribution Release Notes for NCBI-GenBank Flat File Release 208.0]    (ftp://ftp.ncbi.nih.gov/genbank/gbrel.txt ). The GI accession form will be phased out by mid 2016. according to those release notes.

**Comment by peterjc** [comment]
We don't have anything for this in Biopython - I think you would be best off asking somewhere like http://biostars.org or trying the UniProt support team directly.
