### ISSUE TITLE
Incorrect parsing of description from FASTA file

### ISSUE THREAD

**Issue by jysandy** [biopython/biopython#572]
``` python
from Bio import SeqIO

seqs = list(SeqIO.parse('ls_orchid.fasta', 'fasta'))
foo = seqs[0]
print(repr(foo))
```
This prints:
```
SeqRecord(seq=Seq('CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGATGAGACCGTGG...CGC', SingleLetterAlphabet()), id='gi|2765658|emb|Z78533.1|CIZ78533', name='gi|2765658|emb|Z78533.1|CIZ78533', description='gi|2765658|emb|Z78533.1|CIZ78533 C.irapeanum 5.8S rRNA gene and ITS1 and ITS2 DNA', dbxrefs=[])
```
The ID has been included in the description attribute, when the ID should in fact be excluded. This causes a problem when modifying the ID attribute.
``` python
foo.id = '1234567'
SeqIO.write([foo], 'foo.fasta', 'fasta')
```
In the header of foo.fasta we get:
```
>1234567 gi|2765658|emb|Z78533.1|CIZ78533 C.irapeanum 5.8S rRNA gene and ITS1 and ITS2 DNA
```
The old ID was written to the file when it should have been erased.

**Comment by peterjc** [comment]
Using the full title line as the description (with associated magic on output) is an unfortunate design choice to mimic the even older (and since removed) FASTA parser in Biopython. With hindsight this was a mistake.

Using:

```
foo.description = "C.irapeanum 5.8S rRNA gene and ITS1 and ITS2 DNA"
```

would give:

```
>1234567 C.irapeanum 5.8S rRNA gene and ITS1 and ITS2 DNA
CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGATGAGACCGTGGAATAAA
...
```

Sadly I don't think we can easily change this without breaking many existing scripts.

**Comment by peterjc** [comment]
See also #398
