### ISSUE TITLE
C-accelerated PWM code (Bio.motifs._pwm) is not used in Python 3

### ISSUE THREAD

**Issue by mruffalo** [biopython/biopython#654]
I'm running a lot of PWM searches, which have been taking a *long* time. I'm not very familiar with the BioPython source code, so my first check was whether these calculations are performed in C or Python code. I found `_pwm.c`, but found that my Python processes had no open handles to the corresponding `_pwm.cpython-35m-x86_64-linux-gnu.so`. I added a print statement to the `except ImportError` block after `import _pwm` in `Bio.motifs.matrix.py`, which verified that the C-accelerated PWM code was not loaded.

Changing the import statement from `import _pwm` to `from . import _pwm` fixed the `_pwm` import in Python 3.5, but I have not verified that this still works in Python 2.

**Comment by peterjc** [comment]
Thanks for solving this and getting in touch. Are you comfortable making a pull request on GitHub?

Since this is a one line change you can probably do a pull request entirely within the GitHub web interface (clicking edit on ``Bio/motifs/matrix.py`` should automatically fork the repository and setup a branch for your one line change). We're using TravisCI so the proposed change would then be automatically tested on Python 2.6 to 3.5 and under PyPy - its very convenient.

**Comment by mruffalo** [comment]
Sure -- not sure why I didn't do this yesterday. I think at the time I was just happy to record what I found somewhere. Pull request is #656.

**Comment by peterjc** [comment]
Fixed with changes on #656, see https://github.com/biopython/biopython/commit/b31cde41c7297fd001df9a68195270fec287c045 - thank you!
