### ISSUE TITLE
Record long URL if Entrez HTTP GET becomes a POST

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [biopython/biopython#678]
[_Edit: See discussion below, this issue has morphed into enabling debugging when a long Entrez HTTP GET URL is turned into an HTML POST as per NCBI guidelines_]

I tried to recieve data for over 200 PIDs from pubmed with Entrez.efetch.
I simply did this for the id-parameter `id=','.join(pids)`.

This make the URL very long but the record comin back is fine.

But checking the done URL with `print(handle.url)` give just the cgi-url without any parameters back.

**Comment by peterjc** [comment]
This is correct, as per NCBI guidelines for very long sets of parameters rather than an HTTP GET (putting the values in the URL) we use an HTTP POST (send them separately).

See also discussion on #608 about doing this more proactively elsewhere in Entrez.

**Comment by buhtz** [comment]
Please reopen this Issue and lable it to a FeatureRequest.

Because of debugging issues there is a need to know the URL which is used by Entrez. See #608 for some details.

e.g. _Before_ Entrez check the `len()` of the url to decide using HTTP GET or POST, this url should stored somewhere. Maybe the info if GET or POST was used should be stored somewhere, too.
`handle._original_url`

'handle._http_get` and `handle._http_post` returning `True/False` depending on the `len(self._original_url) > self._http_get_post_threshold_len`

Something like that. :)

**Comment by peterjc** [comment]
Retitling as an enhancement about how to access the potential long URL if Entrez HTTP GET becomes a POST.

**Comment by jotomicron** [comment]
As peterjc suggested in #608, it is possible to add a `._original_url` to the resulting handle. However, notice that in case of a POST request, the "original" URL is never even constructed. Bio.Entrez converts the dictionary into a string with `urllib.parse.urlencode(...)`.

I wonder if you want the actual *bytes* that get sent to the NCBI servers (something like the string `"id=200&retmode=xml&restart=10&..."`) or the python's dictionary that is converted to that data.

**Comment by peterjc** [comment]
Probably the bytes sent as the post message would do, that and the (short) URL captures everything sent to the NCBI.

**Comment by peterjc** [comment]
@mdehoon do you think recording the HTML post data in the handle is a useful enhancement for debugging? Or can we close this?

**Comment by mdehoon** [comment]
Let's close it. If it's useful for debugging, it can be added when debugging.
