### ISSUE TITLE
Rename EvilHandleHack to something less scary

### ISSUE THREAD

**Issue by anntzer** [biopython/biopython#721]
Yes, I know it's just a temporary measure and people are talking about dropping Python3.3 support.  Still it's a bit awkward when you teach biopython to beginning pythoneers (on an interactive console) and you're like "uh you got the result of the query, it says EvilHandleHack but don't worry we'll parse it and everything is fine."

**Comment by peterjc** [comment]
What would you suggest instead of ``EvilHandleHack``?

And/or, how about we only use it on Python 3.3? It should no longer be needed on Python 3.4 onwards (and was never used on Python 2).

**Comment by anntzer** [comment]
HandleWrapper or BiopythonHandleWrapper?
And yes, using it only on Python3.3 would also be a good alternative (because I don't think anyone is teaching beginners using 3.3(?)).

**Comment by peterjc** [comment]
I hope we have hardly anyone using Python 3.3, and probably just people using a cluster or other Linux system with a relatively old distribution provided Python 3. I'll look at making that change...

**Comment by peterjc** [comment]
Using ``io.TextIOWrapper`` on Python 3.4 and 3.5 isn't quite as the drop-in replacement I was hoping for based on ``test_Entrez_only.py``, but this is something we've essentially postponed fixing properly.

At very least we'll have to manually propagate the useful ``.url`` attribute, but that's easy enough.

**Comment by peterjc** [comment]
Marking as fixed now that this will only be used on Python 3.3.

We're deprecating Python 3.3 support as of Biopython 1.67 https://github.com/biopython/biopython/commit/d183e6ed5e23dd6399759c0f73011e84ebe03954 so I think on balance there is little to gain from also renaming ``EvilHandleHack`` since hopefully hardly anyone will see it as Python 3.3 usage dwindles.

Also it is likely that ``Bio.Entrez`` will start returning an ``UndoHandle`` wrapper anyway in order to catch some of the more common poorly-handled NCBI errors, see #515.
