### ISSUE TITLE
Chapter Going 3D: The PDB module not at Tutorial website

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#731]
Chapter Going 3D: The PDB module, file chapter_pdb.tex is in the Docs folder, I can't find it at the Tutorial website. Is it hidden?

**Comment by peterjc** [comment]
Well spotted. It was a one character typo, sigh. It seems LaTeX only gives a warning rather than aborting if an ``\include`` does not exist:

See also this much older document:
https://github.com/biopython/biopython/blob/master/Doc/biopdb_faq.tex
http://biopython.org/DIST/docs/cookbook/biopdb_faq.pdf

**Comment by peterjc** [comment]
http://biopython.org/DIST/docs/tutorial/Tutorial.pdf and http://biopython.org/DIST/docs/tutorial/Tutorial.html updated to the current tutorial as of 83a222766610d5ddf93310f9cbd117bfd207fe1d
