### ISSUE TITLE
Change default behaviour of Bio.PDB.PDBIO

### ISSUE THREAD

**Issue by rcrehuet** [biopython/biopython#774]
The default behaviour of `Bio.PDB.PDBIO.save` is to include an `END` after each model, when multi-model structures are saved. This is specified by the argument `write_end` which takes the default value of `True`. 
However, as far as I understand, this is not in agreement with the [PDB format](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#MODEL), which states that each model should end with `ENDMDL` only, and not have an extra `END` statement.  `PDBIO.save` correctly includes the `ENDMDL` and I would like to suggest the change to `False` for the default behaviour of `write_end` argument.
The use of this extra `END` is not only in disgreement with the PDB format, but also causes some molecular visualization software such as VMD to stop reading a multi-model PDB, i.e. VMD only reads the first model. And this is indeed a problem.

**Comment by JoaoRodrigues** [comment]
The END statement should only be written at the very end of the file, not
at the end of each model. The code in the current git version should do
this exactly, as the write_end logic is outside the "for model in models"
loop.

Which version of Biopython are you using? Can you post here an example of
this behaviour, preferably with the input data so we can try to reproduce
it?

2016-02-23 0:11 GMT-08:00 Ramon Crehuet <notifications@github.com>:

**Comment by rcrehuet** [comment]
I'm using version 1.65. In this version, and also in [biopython docs](http://biopython.org/DIST/docs/api/Bio.PDB.PDBIO'-pysrc.html) the `if write_end:` (line 214 in PDBIO.py) is in the `for model in ...` block, just after the line that writes `ENDMDL` which is where it should be.

**Comment by JoaoRodrigues** [comment]
Yes, this was a known issue. At some point, maybe while correcting
whitespace, this was indented erroneously, but it was fixed in October
(2599d4ffc858d61228696aea4770b2fbc95f17bb). Please upgrade to 1.66 or
download the latest from Github.

@peterjc I wonder why the documentation wasn't updated though, thought it
was automatic?

**Comment by peterjc** [comment]
According to http://biopython.org/DIST/docs/api/Bio-module.html the version currently online is indeed for Biopython 1.66. Updating these API docs online isn't automatic, but is part of the release process, http://biopython.org/wiki/Building_a_release

Unfortunately the commit you are looking at which fixes the ``END`` line  made was about a week *after* Biopython 1.66, so will be included in Biopython 1.67 (which we could probably start preparing soon). If I recall correctly this bug was originally raised and discussed on the mailing list rather than on a GitHub issue.

For now @rcrehuet could install the latest github Biopython from source, or make that change manually.

**Comment by rcrehuet** [comment]
OK Thanks @peterjc  and @JoaoRodrigues Certainly I should have updated first!

**Comment by peterjc** [comment]
@rcrehuet Thanks for reporting this here - it was unlucky timing that the fix didn't make it into Biopython 1.66, and we could/should be more diligent about filling issues on GitHub for problems reported via the mailing list.

**Comment by JoaoRodrigues** [comment]
Oh, indeed, 6 days later... ​

Sorry about the problem @rcrehuet, and thanks @pjcock for the heads up on the dates.
