### ISSUE TITLE
MMCIF vs. PDB file information

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#779]
This is somewhat related to #778 and #775.

The current mmCIF parser uses `_atom_site.label_asym_id` to attribute chain identitifers in the SMCRA object hierarchy. This is not necessarily equivalent to the chain identifier field in the PDB format, e.g. `4q94` or `1brs`. On the other hand, the `auth_asym_id` field is a direct match to the PDB chain identifier (when it exists).

The practical consequence of this difference is that when parsing the mmCIF and PDB files of the same structure, we get different chain identifiers and different numbers of chains (see below).

```
Str. Name	#M	#C	#R	#A
4q94.cif	1	30	388	2337
4q94.pdb	1	 4	388	2337
```

I suggest we change the assignment of chain IDs to use `auth_asym_id`, if it exists, to have a better match to the PDB files. Also, because it is assigned by the _authors_ of the structure. We should store (in segid for example) the `label_asym_id` information because it is always useful to point to.

What would be your opinion (@ofajardo, @peterjc)?

**Comment by ofajardo** [comment]
Hi, 

I am comparing the output of a couple of programs of mine (based on biopython) when parsing pdb files and their mmCif counterpart, and I have already observed this chain renaming. The chain renaming is confusing, because for example the information on the webpage (http://www.rcsb.org/pdb/home/home.do) for a given structure refers to the chains in the pdb file and not in the mmCif file. Also, HETATOMS are manytimes re-assigned to new chains that did not exist in the pdb file (for example there is only one A chain in a structure with 3 Pr HETATOMS in the pdbfile but in the mmcifFile, we have the 3 PR atoms assigned to chains B,C and D, which did not existed before). I like very much your solution of taking the author information if available because it would do my code, and anybody else's code work equivalently for both pdb and mmCif, and having to adapt ourselves for every situation.

**Comment by peterjc** [comment]
I've not done enough with structures recently to give much weight to my comments (I've never used mmCif for actual work). If you can use the author-assigned identifiers that does seem best as it would match the associated publication, and be consistent between PDB and mmCif.

**Comment by fomightez** [comment]
Not much to add either except maybe here cross referencing with the Jmol community could help? The have been dealing with reading mmCIF files the last few months too. There was recently a discussion on how the EBI PDBe is modifying assembly mmCIF files in ways that don't even match regular mmCIF files, see [here](https://sourceforge.net/p/jmol/mailman/message/34803015/).

**Comment by JoaoRodrigues** [comment]
It's been a couple of weeks and it seems the general consensus is that we should move towards the usage of `auth_sym_id` to improve compatibility with the PDB format and respect the authors indications over software annotations. I tried reaching out to the Jmol people but got no answer. 

I'll make a pull request in the next few days after making a couple of tests to make sure this doesn't break anything else.

**Comment by peterjc** [comment]
This is now on the master branch - please give that a try and reopen this issue or open a new issue if you find any problems.
