### ISSUE TITLE
Tests test_Entrez_online, test_NCBI_qblast fail

### ISSUE THREAD

**Issue by kaetana** [biopython/biopython#784]
I am try to install biopython first time.
`python setup.py test `
causes the
`test_Entrez_online ... FAIL`
`test_NCBI_qblast`
OS X 10.10.5
I dont know how important this, and will biopython work properly or not...

```
======================================================================

ERROR: test_fetch_xml_schemas (test_Entrez_online.EntrezOnlineCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Entrez_online.py", line 177, in test_fetch_xml_schemas
    records = list(Entrez.parse(handle))
  File "/Users/kaetana/CodeRep/reps/biopython-master/build/lib.macosx-10.6-intel-2.7/Bio/Entrez/Parser.py", line 270, in parse
    self.parser.Parse(text, False)
  File "/Users/kaetana/CodeRep/reps/biopython-master/build/lib.macosx-10.6-intel-2.7/Bio/Entrez/Parser.py", line 352, in startElementHandler
    raise ValidationError(name)
ValidationError: Failed to find tag 'Error' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.

======================================================================
FAIL: test_pcr_primers (test_NCBI_qblast.TestQblast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_NCBI_qblast.py", line 54, in test_pcr_primers
    10, "pan [ORGN]", ["37953274", "51104367", "51104367", "51104367"])
  File "test_NCBI_qblast.py", line 100, in run_qblast
    self.assertTrue(query in record.query_id.split("|"))
AssertionError: False is not true
```

**Comment by peterjc** [comment]
I would not worry about these, and proceed with the installation. The online tests do sometimes fail due to network problems or simply issues with the remote server (e.g. the NCBI could have been unusually busy). Often trying day later and it works, although sometimes if it is still broken this can indicate a problem with your local network firewall etc.

Thanks for checking!

**Comment by peterjc** [comment]
I fixed the QBLAST issue in https://github.com/biopython/biopython/commit/6f90dda74d75bcdcc78a2a9d45461b193fb4b468 - it wasn't a really problem, just a small change from the NCBI which broke our test.

The ``test_fetch_xml_schemas`` problem does seem to be a problem at the NCBI, mentioned on #515, but seems worth re-opening this issue to track.

Recently ``test_Entrez_online.py`` has been failing in ``test_fetch_xml_schemas``, which turns out to be another NCBI problem - possibly a temporary problem, but their error message is not even valid XML:

```
>>> from Bio import Entrez
>>> Entrez.email = "p.j.a.cock@googlemail.com"
>>> data = Entrez.efetch("protein", id="783730874", rettype="ipg", retmode="xml").read()
>>> print(data)
<?xml version="1.0"?>
 <IPGReportSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ncbi.nlm.nih.gov/data_specs/schema/other/seq_report/IPGReportSet.xsd">
<IPGReport gi="783730874" accver="KJV04014.1" taxid="1356405" org="Rhodococcus sp. PML026" kingdom_taxid="2" kingdom="Bacteria"><Product gi="797137454" accver="WP_045840896.1" slen="513">methylmalonate-semialdehyde dehydrogenase (acylating) [Rhodococcus sp. PML026]</Product><RedundantGiList><Error>Resource temporarily unavailable (4).</Error>
</IPGReportSet>
```

Notice the unclosed tags, e.g. missing </RedundantGiList >

I initially guessed the Identical Protein XML ipg XML failure is related to the NCBI phasing out GI numbers: http://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/

I reported to ipg problem to the NCBI, they doubt that phasing out of GI numbers is causing it, but have passed this to their developers.

**Comment by peterjc** [comment]
This seems to be working now - I guess the NCBI changed something?
