### ISSUE TITLE
New BioPython 1.67 SeqRecord comparison exception breaks `list.remove()`

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#873]
Hi folks,

I just stumbled across an unexpected side effect of the new `NotImplementedError` for `SeqRecord` that was added in 1.67. You can no longer use list.remove() to remove a `SeqRecord` from a list of `SeqRecords`.

Example code here. Works in 1.66, throws a `NotImplementedError` in 1.67.

```python
#!/usr/bin/env python

from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq

fake_seq = Seq('FAKE')

records = []

for i in range(0, 4):
    records.append(SeqRecord(fake_seq, id='{}'.format(i)))

unwanted_record = records[2]

records.remove(unwanted_record)
```
If that is the intended effect, we should improve our suggestions in the ChangeLog to also include a tip for how to handle this now, as you can't easily make `list.remove()` use the proposed `id(record1) == id(record2)` comparison, so this requires a larger change in the application flow.

**Comment by peterjc** [comment]
That is unexpected - this is not a usage pattern I'd thought about, nor apparently did anyone else till now, which is why we didn't suggest anything in the ``NEWS`` entry or ``DEPRECATED`` file. See #559 and #560.

If you know the index (here ``2``) then you can of course remove that (``del records[2]``). Evidently you don't in the real code?

It appears to work using a set rather than a list, which must happen via the default ``__hash__`` method (to which we have not yet added this deliberate exception). Also using a dictionary might work nicely, however you are likely using a list to preserve the order. In any case, I don't see a trivial work around without a larger change in the application flow.

This side effect might be enough to justify reverting the new exception and returning to the older behaviour? I'll bring it up again on the mailing list.

**Comment by peterjc** [comment]
@kblin I see you were able to use the list index instead to avoid this issue: https://bitbucket.org/antismash/antismash/commits/7c5bc46f4b8d81db5c6f0f0b05162c05f6dc4d2f

What are your thoughts on if we should revert this, or try to provide guidance on this use-case?

(Apologies for the conference induced delay on this)

**Comment by kblin** [comment]
I don't think we need to revert this, pointing out that you should be using `del` or the like in this use case should be enough,

**Comment by peterjc** [comment]
I'm wondering if we should also do something to the ``SeqRecord`` default ``__hash__`` method which currently means you can do ``my_record in set_of_records`` but not ``my_record in list_of_records``?

e.g.

```
>>> from Bio import SeqIO
>>> list_of_records = list(SeqIO.parse("cor6_6.gb", "gb"))
>>> set_of_records = set(list_of_records)
>>> my_record = list_of_records[3]
```

This used to work, but as of Biopython 1.67 triggers the new exception:

```
>>> my_record in list_of_records
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/SeqRecord.py", line 727, in __eq__
    raise NotImplementedError(_NO_SEQRECORD_COMPARISON)
NotImplementedError: SeqRecord comparison is deliberately not implemented. Explicitly compare the attributes of interest.
```

This currently works because internally like a dict it uses ``hash(my_record)``:

```
>>> my_record in set_of_records
True
```

Should we make our ``SeqRecord`` unhashable, i.e. match:

```
>>> hash([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```

with:

```
>>> hash(my_record)
Traceback (most recent call last):
  ...
TypeError: unhashable type: 'SeqRecord'
```

This would mean we'd get this:

```
>>> my_record in set_of_records
Traceback (most recent call last):
  ...
TypeError: unhashable type: 'SeqRecord'
```

It would be more consistent, but again could break some existing code which is deliberately using the object-comparison via the implicit hashing.

**Comment by kblin** [comment]
Revisiting my old open bugs right now. I think consistency is good, but maybe we throw a `DeprecationWarning` or the like for one version before breaking it explicitly?

**Comment by peterjc** [comment]
If you mean adding a warning to ``__hash__`` prior to making it give an error, I agree that would be best.

**Comment by peterjc** [comment]
OK, I've filed #929 for the hashing issue, but otherwise I think we can close this original report. Thanks for the feedback Kai!
