### ISSUE TITLE
Unreachable code in Nexus.py

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#949]
Bio/Nexus/Nexus.py
The last line below (799 in Nexus.py) does not appear to be reachable.

``` python
        if 'transpose' in options:
            raise NexusError('TRANSPOSE is not supported!')
            self.transpose = True
```

**Comment by peterjc** [comment]
Perhaps some user code used to trigger it via the ``._format`` method, although with a leading underscore is considered private?

Would anyone else like to comment? @etal maybe?

**Comment by etal** [comment]
According to `git blame`, this exception, the subsequent unreachable line, and the unused `self.transpose` attribute have been there since @idoerg first committed Nexus.py in early 2005 (6a403e1e). The private _format method isn't used in Biopython, but maybe it was used in the standalone program that the Nexus module was extracted from.

My bet is that the original author meant it as a note-to-self, indicating the place to implement the transpose option at some later date, time permitting, which it didn't.

In any case, there is no way within Biopython to set or use the `transpose` attribute other than by setting it directly on a Nexus object, which could be done similarly with any other unreserved attribute name whether it existed or not. It seems very safe to delete this line.
