### ISSUE TITLE
Bugs in restrictions.analysis

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#965]
This [first](https://github.com/biopython/biopython/blob/master/Bio/Restriction/Restriction.py#L2234), 
I almost surely a mistake mixing == with =. The intent appears to be to swap the start end to get the order right. I think raising a warning or error might be better. As it is nothing happens.
```python
        if start < end:
            pass
        else:
            start, end == end, start
```

The [second](https://github.com/biopython/biopython/blob/master/Bio/Restriction/Restriction.py#L2236),
Seems to have the intent of fixing start values and again confusing == to =. The problem is that it does not seem to produce the correct results by changing == to =. See pull request with tests I will reference.
```python 
        if start < 1:
            start == 1
```

[see commit ](https://github.com/biopython/biopython/pull/960/commits/7b30e6804811377a3f07732a5edcd4ed9dc376c6)

**Comment by peterjc** [comment]
Both look like bugs, ``==`` rather than ``=``, and dates to the original commit https://github.com/biopython/biopython/commit/05f9ba2d2abdef1ce9babdce70a6db9d12f69d3d

Note we want to deprecate the entire module and replace it with a new implementation (which uses Python counting etc), there's an open issue on this...

**Comment by vincentdavis** [comment]
Looking at the code close, neither of these if statements can ever be true. There is code above to that prevents them from being true. see commit 0016d57 for fix.
