### ISSUE TITLE
How to skip memory error and continue with SeqIO.parse?

### ISSUE THREAD

**Issue by dmenning** [biopython/biopython#979]
I have a bunch of 10GB fasta files in a folder I want to parse through checking each sequence for specific primer sets.  After the third or forth file I get the following error:

Writing data to 0 folder primer crop_.fasta

Croping 16S_Euk_20161020_1_20161020.fasta
Done croping 16S_Euk_20161020_1_20161020.fasta

Croping 16S_Euk_20161020_2_20161020.fasta
Done croping 16S_Euk_20161020_2_20161020.fasta

Croping 16S_Euk_20161020_3_20161020.fasta
Error croping NC_008804.1 Monodelphis domestica chromosome 4, MonDom5, whole genome shotgun sequence

Traceback (most recent call last):
  File "D:\Python27\0 eDNA\NCBI Databases\16S Eukaryote updated 

161020\05_crop_primer_degen_folder_causes_error.py", line 89, in <module>
    for seq_record in SeqIO.parse(fhand, "fasta"):
  File "C:\Python27\lib\site-packages\Bio\SeqIO\__init__.py", line 600, in parse
    for r in i:
  File "C:\Python27\lib\site-packages\Bio\SeqIO\FastaIO.py", line 122, in FastaIterator
    for title, sequence in SimpleFastaParser(handle):
  File "C:\Python27\lib\site-packages\Bio\SeqIO\FastaIO.py", line 67, in SimpleFastaParser
    yield title, "".join(lines).replace(" ", "").replace("\r", "")
MemoryError

The 'Error cropping' message is my internal notification noting there was a problem, to skip it, and continue parsing.  The Biopython error occurs after this event.  My code looks like this:

    for fname in fnames:
        if fname.endswith('.fasta'):
            fhand = open(fname, 'r')
            print "\nCroping "+str(fname)
            for seq_record in SeqIO.parse(fhand, "fasta"):
                try:
		            #do stuff
                except:
                    error_log_handle.write("Error cropping "+str(seq_record.description)+" from "+str(fname)+"\n")
                    print "Error cropping "+str(seq_record.description)+'\n'
                    continue
            print "Done croping " + str(fname)
            current_time=datetime.datetime.now()
            loghand.write("Done cropping "+str(fname)+" at "+str(current_time)+"\n")
            fhand.close()

I have tried changing the code to get around this error by using the following script:

    for fname in fnames:
        count=0
        if fname.endswith('.fasta'):
            fhand = open(fname, 'r')
            print "\nCroping "+str(fname)
            try:
                for seq_record in SeqIO.parse(fhand, "fasta"):
                    count+=1
                    try:
                        #do stuff
                    except:
                        error_log_handle.write("Error cropping "+str(seq_record.description)+" from "+str(fname)+"\n")
                        print "Error cropping "+str(seq_record.description)+'\n'
                        continue
            except:
                print "Error writing to "+str(fname)
                print "Check sequence number "+str(count)+" in "+str(fname)
                error_log_handle.write("Error writing to "+str(fname)+"\n")
                error_log_handle.write("Check sequence number "+str(count)+" in "+str(fname)+"\n")
                continue

            print "Done cropping " + str(fname)
            current_time=datetime.datetime.now()
            loghand.write("Done cropping "+str(fname)+" at "+str(current_time)+"\n")
            fhand.close()

The problem I have now is that the code finishes but when it throws a Biopython error it stops parsing that file and continues on to the next file.

Writing data to 0 folder primer crop_.fasta

Croping 16S_Euk_20161020_10_20161020.fasta
Done croping 16S_Euk_20161020_10_20161020.fasta

Croping 16S_Euk_20161020_11_20161020.fasta
Done croping 16S_Euk_20161020_11_20161020.fasta

Croping 16S_Euk_20161020_1_20161020.fasta
Done croping 16S_Euk_20161020_1_20161020.fasta

Croping 16S_Euk_20161020_2_20161020.fasta
Done croping 16S_Euk_20161020_2_20161020.fasta

Croping 16S_Euk_20161020_3_20161020.fasta
Error croping NC_008804.1 Monodelphis domestica chromosome 4, MonDom5, whole gen
ome shotgun sequence

Error writing to 16S_Euk_20161020_3_20161020.fasta
Check sequence number 6821 in 16S_Euk_20161020_3_20161020.fasta

Croping 16S_Euk_20161020_4_20161020.fasta

On the file 16S_Euk_20161020_3_20161020.fasta it throws an error on NC_008804.1 and continues parsing until Biopython throws an error at sequence number 6821 in the file.  At this point it stops parsing this file and continues on to Cropping 16S_Euk_20161020_4_20161020.fasta  Note there is no "Done cropping" message after:

Error writing to 16S_Euk_20161020_3_20161020.fasta
Check sequence number 6821 in 16S_Euk_20161020_3_20161020.fasta

Is there a better way to write this so that if there is an error with Biopython it skips that sequence and returns to parsing the same fasta file?

**Comment by peterjc** [comment]
I would first double check the "do stuff" section of your code to confirm there is nothing building up a large list or similar in memory?

One technical change is catch the ``MemoryError`` explicitly, rather than any error (even for example the user pressing control+C to try and stop the job which would be a caught here):

```
except MemoryError:
```

How much RAM does your machine have? Is it a 32bit computer which imposes additional limits on working with large amounts of memory?

This opossum chromosome NC_008804.1 is pretty big at 435,153,693 bp (more than human centric tools may expect - you'll have trouble using the default samtools BAI indexing here, use CSI instead). That means at least 414 MB of RAM just to load this as a single string (one byte per base, which is what Biopython is doing internally).

One small change you could make to your code is to use the low-level FASTA parser, rather than the object-heavy with ``SeqRecord`` object based ``Bio.SeqIO`` approach. i.e.

```
from Bio.SeqIO.FastaIO import SimpleFastaParser
for title, sequence in SimpleFastaParser(fhand):
   # do stuff
````

Here ``title`` and ``sequence`` are plain strings, which will save a little memory, possibly enough if your machine hasn't got loads of RAM.

Also I would try an explicit memory garbage collection, although Python is normally pretty good at this:

```
import gc
...
# after each sequence is processed:
gc.collect()
```

**Comment by dmenning** [comment]
Thank you Peter.  The do stuff is simple but loads the entire sequence so I am getting the memory error.  Below is my #do stuff  The function is at the beginning of the script, not in the loop.

    def get_degen_primer_position(seq,primer):
        pos = -1 
        while True: 
            pos += 1 
            s = seq[pos:] 
            m = re.search(primer, s) 
            if not m: 
                break 
            pos += int(m.start(0)) 
        return pos

    try:
        line = str(seq_record.seq)
        line = line.strip()
        line = line.translate(None, '-_ ')
        fcrop = get_degen_primer_position(line,primer1)
        rcrop = get_degen_primer_position(line,primer2)
        if fcrop != 0 and rcrop != 0:
            line = line[(fcrop-1):(rcrop + len_primer2 - 1)]
            output_handle.write(">" + str(seq_record.description) + "\n" + str(line) + '\n')
        gc.collect()

In terms of my system, I am running 64-bit Windows 7 Enterprise with 32GB RAM.  I put in gc.collect() after each try, except, fhand.close().

I changed the Except to except MemoryError: which works, but has the same effect, i.e. is doesn't go back to the original file but skips the rest of the current file and continues with the next file.  The except MemoryError is under the first try:

I also tried changing for seq_record in SeqIO.parse(fhand, "fasta"): with for title, sequence in SimpleFastaParser(fhand): and ran in to the same issue above.

The only thing that seems to be working is doing each fasta file individually.  This will work but it would be nice to have the script continue after the error.  I had previously tried a version of the script where it would go through 3 files, do a gc.collect() then start on the next three files but ran in to the same problem.

**Comment by peterjc** [comment]
Your more general question about how to resume parsing a file might be best solved with ``SeqIO.index`` which lets you parse specific records on demand (and thus avoid a problem record in the middle of a file with a try/except). This does seem overly complicated for your use case though.

Given your machine has 32GB of RAM, and you have 64-bit Windows, are you by any chance using only a 32-bit version of Python? Otherwise I am struggling to see why you might be hitting an out of memory error here. Nevertheless, there is scope for improvement.

Its a shame that using ``SimpleFastaParser`` alone didn't help enough, but that would avoid multiple copies of the full sequence in memory so I would work with that version if possible.

Also, explicitly delete the big string before doing the garbage collection so that the memory it was using should be free immediately, e.g.

```
for title, seq in SimpleFastaParser(fhand):
    fcrop = get_degen_primer_position(seq,primer1)
    rcrop = get_degen_primer_position(seq,primer2)
    if fcrop != 0 and rcrop != 0:
        seq = seq[(fcrop-1):(rcrop + len_primer2 - 1)]
        output_handle.write(">%s\n%s\n"  % (seq, title))
    del seq  # free this big chunk of memory explicitly
    gc.collect()
```

Something else we could try is tweaking the FASTA parser, this line:

```
yield title, "".join(lines).replace(" ", "").replace("\r", "")
```

That builds the full sequence in memory, then removes any stray whitespace. I would hope the ``.replace`` method wouldn't make a needless copy in RAM, but perhaps we can avoid this explicitly?

e.g. in ``Bio/SeqIO/FastaIO.py`` replace this:

```
        while True:
            if not line:
                break
            if line[0] == ">":
                break
            lines.append(line.rstrip())
            line = handle.readline()

        # Remove trailing whitespace, and any internal spaces
        # (and any embedded \r which are possible in mangled files
        # when not opened in universal read lines mode)
        yield title, "".join(lines).replace(" ", "").replace("\r", "")
```

with this version which does the cleaning line-by-line, which will be slower but ought to use less RAM:

```
        while True:
            if not line:
                break
            if line[0] == ">":
                break
            # Remove trailing whitespace, and any internal spaces
            # (and any embedded \r which are possible in mangled files
            # when not opened in universal read lines mode)
            lines.append(line.replace(" ", "").replace("\r", ""))
            line = handle.readline()

        yield title, "".join(lines)
```

**Comment by dmenning** [comment]
I updated my Python version to 2.7.12 from .10, added a del line, and shortened up the output information with %s and everything seems to be working now.  I just finished checking 11 10GB files with no problems.  Thank you very much for the help.

**Comment by peterjc** [comment]
I suspect you are using a 32-bit Python, which means you will hit memory limitations from time to time. But good, I'm glad it is working for you now.
